apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-staging
resources:
- ../../base
- namespace.yaml

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: f44576da366b33ce971dec26878c95486703717f

patches:
- path: patch-deployment.yaml
- path: patch-service.yaml
