apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-staging
resources:
- ../../base
- namespace.yaml

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: 6b8a9235940840bf56c813cb5d1cdf637aa90ee0

patches:
- path: patch-deployment.yaml
- path: patch-service.yaml
