namespace: messageboard-prod
resources:
- ../../base

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: 99d44772d74f4afa4639021e629601bcc7c0dfce

patchesStrategicMerge:
- patch-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
