apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-prod
resources:
- ../../base
- namespace.yaml

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: e16039d4c214ef621085b0f5751166615e1af029

patches:
- path: patch-deployment.yaml
- path: patch-service.yaml
