apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-prod
resources:
- ../../base
- namespace.yaml

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: da4ee2088bf5821822df4f7e9b3923416f0b97d2

patches:
  - path: patch-deployment.yaml
  - path: patch-service.yaml
