apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-prod
resources:
- ../../base
- namespace.yaml
- ingress.yaml


images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: ae9e76bed2429072da8bd323793d559af73ebcac

patches:
- path: patch-deployment.yaml
- path: patch-service.yaml
