apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgB3Pqi0ypBt7QgYqyp29AfEMucT5fV681KySEkdsWTGDRDXjfgwQOQpJl3Cqf4162uqjCrKjOXAMhA+4JkOyxfDecIH6d+QPwrp5rBXx3oCmbEScVRYEP6TUJxFUThRWGu5tUdroEAGZTgWr3H+du1qNlpVdpnZBzJ440yDHMsDvwyhWDUJP2dnO9RfTVMepdwsFw3XKM33Fr0eXqOD5cUUuBXRPWi7X98pCTG0SPEskEjHtPV9zUERkIQFocbjfXLKb99vAD8vnK9qbo62Np5ErY8yTUmrT8CY+CxYAlblQUDlKxkzG/WjxIv76dFRCC0qcZWCo2vfCVAUGKOg+YWbGnJd0qjS1XWVyYjIe+SJrWtczoXHd7D9hYuJu1MHtvhKg/fyioWM5EXiJmTxIh7APcFSCmoYKZOfyjISfDVlUHpsk1S4Wj+W9ImNK2/V91PseD+y2UEj00ip31AFBFymNYOmtexCFdG93pYQ7scS+GK5BudsfcUK3HExA48jwrhw1cC2MV5vzhJNuCRhRYQ2vqjfeCmZbkIC1wFhlgtdCY4ONcjJVHwk+gsFbelTeb19ojeQ9QD92ubjdqiVvLf3fW/+x+MaMpjNbLkosSSN628xK/cW884votJhSrHHwiQ57C2UAvo0gyrvcEyQCBwaBFYL1DuPdzuBF9C5eDdH2rnZViTTyViRXtJFLunXl+WL2b4EzKYedpUlAXUQjSP/16UIXqaawUxaeg6tLHwwL46ojY49b2R5xIbVORl5525W1K7jdMxyD+/4LgOd6gQpRS+4So23uBPiXeheY/CBVfa+2YT/ECtg0ScfLFuVGMBIauB9olhCelWvd/5MrX8OPP6OYTihDaE/ndGe4VUIg45un0G1uN1brQwsJ9685elOes5moZBhzUzAC0TsR/Dtx+laF66SgtmQRT1eepQSAiHPB96xxYZhBHBGYQtn6fc+eyGknfcpNOgakGTbPgBqJnO9azY=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson

