apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBsdRrJaZhsIwh8koNdD8s0yXqyPr7GENYfgCGpWumCpGRN/VuKCyRIHLdOWuPmu1aauLA89Jb0rd5O2Sf7DelftpBrm6Uxo/nBl/6uwf7f4dxTpL+MXyGdF/yQirrtTtIJf1QJl9ImMdevqQlD9usEKSXvLsJ5XB7KrDbljbd1BWh386XeQx8ZMmhV+7R2O7m/RqXi5MIkTg6/albBs3YdY3Z28lBBIfxP8spjsYOOkPCYIczY/Pv3cAyWNWoVxWinwnEFmwnkxQLc3XWGn5/b3gitKmXtWdSB6u5yFplN+kv4uFDWbT/v+T2pLuQPp6T4D3WdhsXx4xKkJeAwn8d49RJ0oae358S2g09PEMVNk2D5ACD8zxizx5nMD4nPJu3Qv0iGOByX1wJkLAvkIa5AmP/e670YUnhHzeCCWCqe9P22QKMt2js5dWAd/CPsdLAc7uRdkN7gEbx6l/HJZ1c0Y3wz6X+8fsVRTgtn7xQ+soV/aBiNQvzL2bglTj1IVoSIXBkWSspEO/eynsXchhUyHpt3J7MVGpEu5UZW9ZVXjbLsQ29FmSUBx54599J+qOl9KRIFvw3+kD97DIv9EeRUTlyfpXx8k07jkhJqu8xyL5zACgkBsZ/6P7diRwrg5mTw5k0zgAjwEKSnpIKPkaWhMtMM3CB2gSwFp3Q7JVXWo5HHC71a6b/TbcOTWB/EUk2D1RaHkm0W9WEyxLAwWNJpkIHZmIzhJIhgOZVljTjPhuwXz172h+659qVmDEJuR6ZSGtPVHXeKBvTRbY+VhavreMEiAd8dPtlBhMrXDeFs2T6UxOywtrwQQWhlso22egJQUVXefhneQ7dws+yvLiNuBd100mlXbua4UZGCldsycw7TA5TQd/fGCLzpkbu+DM8D/LFN6PB1SSg4YVcF1n8EQwizu6KhqDr3vRn7Lo17SUYsuoQ3mN8Wy9BM5yVfNK1I24FdONTx0Y84CmSamKvxG1ppWzs=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson

