apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
    version: "v1.0.0"  # Version label for tracking
spec:
  replicas: 1
  revisionHistoryLimit: 5  # Keeps 5 old replicasets for rollbacks
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        version: "v1.0.0"  # Propagated to pods
      annotations:
        prometheus.io/scrape: "true"  # Enable Prometheus scraping
        prometheus.io/port: "8080"    # Metrics port
        prometheus.io/path: "/actuator/prometheus"  # Spring Actuator endpoint
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: my-app
          image: gitauwairimu/messageboard:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # Resource limits
          resources:
            requests:
              cpu: "700m"    # 0.1 CPU core
              memory: "512Mi" # 256 MB RAM
            limits:
              cpu: "1000m"     # 0.5 CPU core
              memory: "1024Mi" # 512 MB RAM
          # Health checks
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30  # Wait 30s before first check
            periodSeconds: 10        # Check every 10s
            timeoutSeconds: 5        # Timeout after 5s
            failureThreshold: 3      # 3 failures = unhealthy
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 15  # Faster than liveness
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          # Optional startup probe for slow-starting apps
          # startupProbe:
          #   httpGet:
          #     path: /actuator/health
          #     port: http
          #   failureThreshold: 30     # 30 attempts max
          #   periodSeconds: 10        # Check every 10s