---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBs9mL/d0iNzWMMnaKkJFf/za0Vddb2awFiRFveLW+40l8b13O/U2vRklZbXkYOzqkopYwSGoYjVro2qnD5KNZ2/oRG6nTjeLMsWDkAjUSiJcxp269E+cYFTQSJ7phvx3/gcT1QhcRXeraVANKoVljKX1YovQ5AGmD03K2t0sZVvPanhG6X/h6L1Nt5hNGaV+tLtS2ztQtJO17Z2/Oq+7eJ51Kgt3Od9aidfiyooHxPcjdBa3zxNQWVgqjgJ2AkLPHWpCkj+tcD68w5sQBBqLZlQ19tfz+26Jun6YNGvU9c0zoFdG1SPBygzV8YxBNYaf0uNWD1nOCrSlzbfZpFklKmi1Kk4aL8tGs5w1/Qk44HK/cHnFnjrE2DtvbRQTufOCQIqt9C/KmDBAu3zx/8WY8u1PuEHOGl8ZHqI8hmtejniwOyZ2snUkRO14HnGtWhO5c8YdIHMnN29DFvnJvdTdu26zfsI7Qi0dj+tfBQZJdciRVVjjxmfmjxPSFniBjq2pctVHoC51IvOHJ0feo4zMi3dhgAEamLLHc9Hw6WM1EYStSjlL9vpR/WvWz0zFdPjuZ5sBbxC3zq9DxGT5W+T+G9SPq7J8XrF5C+tUmiZEDKXgiLnXgrlv/j36VWJkuJDdpQ0iMler+r+nUnYTe9fFdfcuF/hGDMylFEwrxqqLOZhfqs7WkBhXVqRF3iJ6b8aj79bXRAvVeuS5IPT9jTOOxWOt/j/BT8CAgwEsfYuygZb6wKcAqpb1MUqbIfAM9UuG2Vdj+50NARwEXYMVye/gS+4DaQjmydNd3oLjG7BV58Od+iHW1cYKG2l/5Jnkc6DrVBo4OAol3Y19cJWlctdK+n1G/yV1z9YDJiqiUEyYytnQInCWlOVolFNGlteD12bn6n8dVVjWdOyST1mTODRceITMPOwlB8kr4erHr6Vk93Q4p2SQBVKy6bu1nJZmQ2zR5edtFuMPtXcS0r6LRribU3DFf5VmA=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
