---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgDWWy/wixnev/hLHX80AaAU7puXJddO6UVTbIUVMQDtYkOX+yJ7yy7ZBjL2s2mrLSrD9CCcBFUOw9nxkAduOIWmZ0Xxr9LscFHTsSnaRRizCdjftPz0tn93ZNcQ/b4lbSaqauZHvJgjdETzDCRF9OSZ8wwAElH6nunbH1Q42LZUOv3cnpzt8iW4xplYX4nEgESf+YZQp6Sxv3BxNMd/KD4vZcbrWErMDuq83fcgb1zpA99olGuxxZnHTSBF9KFcjsH4wpUMXg/5id5cF8fhdejsgIJTJIqVTTmy3cl1/gQIDRVKhnjGDXtqV7u2HwOJxUwiRHgn2OyYE/THiT7M/fQAG3cF5VBY6Ns0okasV+FhAbgDVX9a9QeWFTGaPy5qYZuPNNzFGG1GVTWQnZqNCxq3GcbH0/bw2RzlL7PmAtHxqaq+enR/UY3sTl2RDZZ1hewgBUeWJc0O6+mcDvc5HeBuoXbM6ZWt5ZNZkKktWuu0GpxFJhPU6ZQv7hWREZh+ib7XKex6LmNs6EaSVSJ94hlHa4HS+tNIcorlsCZJsmnAewl6X+e2KVdWVPWAnb0tEv/lGUf2oziER2HUe8zu393gCpYhfMhSqpvd4DFqJEEG1G51eh5gaf+vhzwx627aPbCLQnJF0QiN93luZ0i2uUuu54gzgsg1rmEf6vYS26ynFqDqVVaGzWJnBaWKM+ISHBwIHrBz+BUfmh8CzkGSyGbm6b+hZE9dOA7y/wpk6yrYvrleT4/cjOFohZoRPAh0k1t4s90laworFnrq0ccG9jrG1hS+d6HyawQhk1LIsS4gDQns3YQFevEihGyEPwD6l+Ed0KT5NuHIEz1eFFI4Nry9rrNx1If/wnKAkkI3une6724f5nefeT5+Fo3qwMBWUvL6KfOIqh6nUQEQjLaNvCq8KQDYVmh49CwVA/1oroYMllMvM8Yw0Y2wUt0xwhnRpCYUfqFRLJTJVgoWByx2/P1qWuHHLgM=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
