---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAPQXqjohx0hv4t5I70B2PERlnlUCURX/GpPBzWKPEt1MrQ2QzUq0pZmNrdkvUgqnd4cK7sr6K3ZeQ5RhiYPMwn8BW4rqNX0pU5dI9CWEk+wkTGSTufwQiBkKOFjanE2zS7SxTCF8dduE0CByy8+HWfKConC6eXQXQKfb62I86s23E1iTyOdRm4mJcFWPtMNC2Fq2lOp38bjmT1swDNJHBNhcCNxRQLhnryvfSV/bi4ojcv+Qw/lHL77/QPDTbPzuFNTmAL/qdt7dBKDJx4n1vsE5uYIMvokoB7ztI6GHybB/Xi1QbsQQbGa8MdV6DOKQnRxHSdPW7VN8ok40hEdcXdC0pVFCJLDmuw3Icdi44xIrFWjMwxb134HBN/R/hSHsDTM72HccbHN6ExKIDAZTaCoqe1FGODFhszMkGFoSKpM/5Gr02/gIKnu5/3m/zNN1FJTyDiqruFNFO5La1KF4sMgfGgv4jKpGLHSp1PbrNGjI6LdB+PF57Fj1m62nUeU4IRMbjrraO1e/9dcDJG+p6733d7NpwD2+PlqPEtF9ZTk3mrk/X38Dndqv1tYJjY5BnHYA4+DFpVDU2pEF5zBJIeCs9PeGMyIftuK153HEN/Pm+fKVv/pWKDvuQM1EYK2IxqoPOZIzhdEogTJunX6zZYohte23VGGh3QDk36jgkrEttxhd2ynne68ZHSHereZqh3YeLcZ5sppn4pG5st4KZrYTz24y47tOP7vsK2NrQ6J1EGTDFfJ+FNHfR7ppTC3xhF516/cafpQnSpAet49Qba3vJ+52NGYyj3tmkFZ6jXQRV9pJ7wufEu9m+4lXs74jwMR5HSE+9pFOG8Izw4ys16Tbk2dpcusrlTUDqbGmpHRffdQj8JWd0Jq+P8s6iC2EkfyDXCP4k2gIXsWLBBNShJPiYiO9X6EAV8oZYvDxRTTAq4A71PPFOwPvPIGx6phWPlreMgRFy+odTBu9xcwfxG1MiqRrk=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
