---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBE2eZvMvs0/DrO10rVX8qp3c7/FY2B7/Fn7pJyveCNYV4e8fDRaxcq/ka6dlzPluEY6grIRbMqQ3vO8Q/i7sW7BVSeoUKabj7e6rAq4LaqRqLP+pnu1NDm1afGv6SWnF06x8QrSyKzRkE7pgrMa0+HN9NBhUtvcFeNSliMTbLYbYM9BcmnJOV20DdgqiR5HWlGcAkDhkcdw0zOtzVdQTHupODDuJ+TYAEKDp4Qsmy8Z0lpCGncyw1czJCltcp6EFuj16CJfeXfzE4vB7fTQWapf7uUY7YES/T+KaR0F3rGlGm8tBd4bkt+SI5ouxe0mqBnRO7a0zuAzpc4ozhRTWdSMUCaacnVdG6gzykgRnooMYR+FbUlsb6eMgIjWAxtyThp5pU2MLHzh/B+XjTk7bmJAKnX/V4v5RHa2eQg0pw9XcOQcUbl6nunD0RQv0bfQuxhWndfOVtg3hFc+1gxkyFXakP1/BoGZm8O56sji3Xr3DjfR+kg141DkfHou+Kigi8p9yUWU2P/3cn7iTI8qDzRipKliyrDiX3RjIbL5Ev/ZWwHZz45ZynZ9XIQA55f7rcZBEjyPJtp1dV8hcL5nDWOYbOp0uq0ZbFvjZjLGzGVx6ijgX2NAAjWAvQRplIxcYhBls+tmXcHCuMkxrc0hWd4G/eg40bG/pQMRd8xTKukOmMuJWbOoz+FJy80W20d/bRCOqp17Z297GrhBoanHROiZpgZ3BwvH5ZhCZwVe2dERPx03LHAf8AKOb/SikyEqEa5pvzQTybf3Jnh4lC52Se47jHBw0RsoZRKXeN44Kk57g1zYYPzGfOJF8uoRnMKcux1xGVLGi0hs4X8rd+bBf+5i+z2DLAnSsEJ6McUNQpQFFc5lyAvUgSYsSOqiWaRDtG1lPNQzO2ULXrJeJwiN08IpbzG0/4q7Cjx8WAg10igPRYq8z3JUbRHBOQkt5gqEU3MG8xoQ5ovX0YPL9897piTlSORCUc=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
