---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCDSo+j5utlsblBrt4LoEKZ48nXdsow3l5zl1oggO3cAFAw/y/KyuCAa+nv/6o7MIttEsXigh/y7Z2L8nAnE0fVwm1FKyLzkfomhpQCczgrV28LhAW1Hihs6HjjvlEzKr8gM8xJjfAvnSaASCp+aE/i/44eT7bzZ0CkCpiFGJat8emhRcAIiOlSip8tKCM7wV/RKxSxajLo3N8IJ/CMQD4JUIdoS9t72XUZEqaD9F2FqjPD0SpszY4oiQdietOjSWYvCmy9M9jfBZgGEpABiGhhVJcAkWd6G/J4d8etjo411y7HhpKqHG+GDsDNWVS5R53hn0n/qVyGFAH6+KTmR42edERapu4Ti4U55/uqm+/HkemBBok5EdmsjSfUJ1+dRq3G2sCzAjNTK2Qbk4UE38PU5k1jja/70V+GGRbxCEDf6ghjv8jvSQHNgZyzc7JDJLxhDCLaxhSW7Jw7Y0twRZNPVDfVkyjctqN4YAbRaoZNeGQMYM9ab3lJG2pfmZLYkRQ60UfufD6WvAmiBYDfJH5hy9YGbYY5xgnZve/40KLqKpUZPz4jL+quJqiYeClMqxYlLMfTeMNexJsyrSmEOObnnOmN4Hb49xtDXzWoX4lzH2E2gMc57DQdDfd8QOm+tfsIEV6tgy8JacdE6Qc4ymNnjfKKWul8fkOyIJaONqIV85R53frJG6nfAVY5pkZwC/KlRlCFPfrU4U9Z2DHrYYckRIQDroFxixPpFZveF6/FG2JENTmQBtxxYQtjYoOn/xbSC/fi1bCDQ3uZKqKhPbvYfF0xd/wO9C7Ml+FnaBAuqbIJYs69Dr7WGeoH5KjA2cbe5cAl+UoYBYhN9McOmI2FbhN2O2I/c638vPctsjGeNNWM67pD5jno75yPCaUChxCFizMUQU/Mb0baxBag9YTu8a0vK5nJPshxo2S8Y7OuRlDv5kANO5LsuJG4peUJjeV0B9feJiWifl17McV+f0sGrpjqFQE=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
