---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBEC8w0qleJ7SiG6tvtsv/gbJMIGBgIwjqKGRtF3g+SGXI9WcOQhKOFQv5AM3XFdrbkqQWCnc3ZPZ1kgGRgWGLohOMZ1zWgLvRbwIw+URoBQgyIh+ltEEuzbUwoSMbdMFDnrGjcNo2mZezmR3v/yjhWnei9XGa9srZ3y1e/FMuUXGEgjGNOvGCBdloWR5X3dZg3NcqnBLSAkPgjPlppSfZe/l9Rob/1i9pQfKghekwY9pl8/vAl28S68kr3SrXu//cY+291zE9BuS4IufzVqF4I1gOWHCkh8LpQCYBwvqNcnzaJVHVmqQMgVlnmjGoNHYTkYMqC7/IMFX8li+8FF+zjYXMUPB7aE6vkXSiI/jPo3PZjiJYNWM+sXYXn1HDDWFjMqXSVqL9mwXuScKq7OSoROXhLSq0qXJqPh3CG+CjfBzzihbIrWYWSOAbFMNY+I31oRx7mLTaTT1VHgnuly4bC816/2/QBxopxT3vQxT37WCBZC2hLGPL4conLN3ErwrsTmCmYTTPvekQpi6avy2DYSHTmGhosS7P1L2e0x8X9pfNal0ed/9Rk3+tQpaK+EhWyA4csCsT8rgeA4ifA8WPpE1bjZ8R4AKKSptQyRKPXgkH4J+cvS2pEHypxhyyLf1p0ra32cW2SWrr09LpsqWxnbF3LF9ARDhXG53nZ/2wt4tVVoa91UtN/1ZmOsC15julLnufAgxc+jrAcuHW26DMyDRxJ/9oFWbhfbjtzNjX3w/RY+O09LX+LNVW7+WR0iBHE1hNlTpcv2dqchYRUtrDhm2JkBE4cIIIzDEulLTKdk07jCb4CYlWYbCHENkr0W0lq/6JtXq883RdfAQNnGeUeQejmJEfjUMHrKYupvlqgPHVjlXY0aQc/v+qtR0IzMdHjNvyvBrWtVF1Eh9sCYA1wIiKClyW64E7kYrQ4g3qNHFhrMZgbU2kAblTdao+Le0uBu7NtyyhMaKR0o2P0wuNudb7UiEY=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
