---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBuYgPNwB5pDbK10LHHL8KI1uJ1nqVNyiWQPe21fl7c/Ra7V0dXJurMPopCDFPG7qM/hH47mvEvPGU5glb+yzi0Of7hVPo7JLdumgZ4zOWBLsVFQ4ohFRB27Lr7NSF5hAGqNPPLzC5Z9x8ihTvzNvilozip/5DpjodWiezjkI/NLxt6NCqLcG0VsC96EZQbHc/+6y/aOM7T0676LHdPashRqJamjTfLUuL0hC/uyDuwMCJyUgmw/MAkbf2WRzunC4/Jcs6VvvN/NYyNb1YN4DhTU/16ufYfJDRKXRmbhZmRAZHGy0s/Kymlh0bw6rxS7GGn8qA0oYJn8oFe3X+PmSQ0r/F4QLEwW2adOy0r0PRyYlxnBvniiIyYqlemiAP1QK/hnfYTwe2DJzoTDkQfKdeeWcH/Syqihw0q+VE7ceI7AXssU22hAJeXKixdwkA/vwOwS3qenapx40gkFuscWVAunir8rauYB4JzFku9pNfZQeCQT0kvMANRzQv0M9EvaxD9nnTKrPa25FmI25VDRttKvFuApjdUOsVW+KyTONTKFlhYmnGrY6kvvPevCPTALnX1MiNTlvpMwgVHdiS9mAfsjvja05Kt+mN9QdcUfjYavSjB+v2p9EKeodaJ+4bvoQdtVdRYSGzYN85trkmhelWgsOXBz7G/kqJ1ca8+GG1hk+EKdSfpYVYdc7lorTk3AJ/X2Ug5tfMCsxOo+9WFupYAn7jYp4cTuaSSNWJdl1tqvs2wUh/VFD8X0xeiR8O4SxYOkRwzop56Pic3gWv7IZpriFhwL0Qx7trI+CDzc/6Sq7qsx6rUhFZ+/BI6a23Khkpy7ylrycWjXxFnqD/iX82E8ppNHo2Q4PZg2pHNVOlb/1OXEqXVG2Pc9TpO85841VZBj7sA+hoSBoqBPwtLaoN12uKgZIvA349qQG+ZNo1rX7ufqvx1mFo9hsrWzcczl5X4c4kz9+Nfz2QZ8S+BalWdb3KFxxE=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
