---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAWRGonBKXvwq30wv6oLua5MvRhUgjO+yG70F9+vP/gdAbXBmpvHmwbeFSWOLjZCoJ4gq1CgLHgOGu+Ssj0wAV9YjadPsQLHDpnSitQRuHxgYZKPgyP5QYIXMVOmppySiXdk2LzCl/hKkHdBtuq1vJTdWFRBLt+TRQeUaU1cX6QDF3EhEVAe0ZHxFZ+pek82tZS6UsVWU+rfcd5E4lV0G3XAo97fHF/B/hQDyw/7quoM81hJa9ueKY4vy2BLDRrFF++7LVCNm/yKPDK9GRIAIK0d3FwsKzgaK1t60384TWNoN5THNy1yWTtST6igGI8rpqVaRr7GhZrKxdMqXJfnj6ESv1tj3pmE+FHnxTezwHJxGit1lzs96rJKdZ3T42yA7qnFcoYQMrLn+Cy39t3y1sfapc3xzKdJC8npfsDOZHq9RjGOrtRdljzCZAZcpOJE8Slk486Z69CDtV+nslEJJSaocWPrFaL1be4zJtJ6YIURrSzslAz/tVomjQO4Wu5qZTncOPySqLUV4rDPYbCKi7jdrx0gcuXXj+KRWYq4iU5YLZeNs7xofHluaWs+RulNjyIezlIdXPPD9VB6xJQkX2nh8gN1kC++T50t8yfMqET8NMrBQ3o0pHbIgJSalUnQJjh/VzCjHs08OShwFI+Hr7fE9iwcudNwjfsIpWlodyoiTPJCwsSQntDZbKKzMvyHvJFlZcLxc9umvlrSra2agh7jmTIxoRkMi6kJ206/P7mOK5kMuz/b+KvIJUcCgnqiIniJS7mB4M1TriQX7gCHCfvTvbc4GaFm4wt7tDf0ZPXX/LI2coY3gmSRXyuKMMT17y/+7l8FHO8SqZvy5LKQOD8pyYaOzrXuHjq7ITIEWTDzepn4NzmCtpllEnfSujaLTpRrDY31swmnoaGkmLwKSkikftUFYbr13NHDPq2r8c2S5O+UH00s3+dWRWZRxLQI7n5MFrjMTnDqV7kDHHM6Aw8oD09aYY=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
