---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAIJia2Oh4etbJYosxlyDUb1PjKmJ5S4DglUUIyuDhLI1G2bU1MKB+BMF37gVNQgDOHqPPSwum1TtaqMKvNSGhuP9Qbjs/apkR5V04N95gZ71g7Q5ADTFCgaQPiU09hq2VBbhcwDK9xCBNwl5gpFQ132BwLqd9rueL77gL/MKMzg6LC4+oj9Nz5QTlvWMxDcBGJF3h9ZwcE41SVaoZy+MYpGyXdfz5R50/0vAyhgHeH7Ka4JInPw+cgf4LVd4urbdqFYGT7Ofk1dFJYwXCvNthyTRk7oRNegWv0iGXKqSd0MYH82GBaLRU/v5ifENPj5N5O0JKJ5NFE/8s1+fl3k2+YPrrUnDJ/5myxv2E/OJnZ6hqcsZ9HVtwSmMjG+gUT0INVUWXK8IVvCiqXqYb5JF+jmP2ZQ9FlOHYplrIFgPrZuhXYEPcyXkTcZVquuEqQXJcLlum+MyBvAZc+08iMU3DHykLh0smb41eO2y7FSosVbiU7y2c4Gm0IortJm1AZkMMgpor1icivTa5SPMc+QOepVyYicGPrRseVlcVYPoV2ovdSoLV7JNfdUS9bqBrwZ9pfhH2nvgxTdD0wYYjpSbo/VgLkJnRBwNnz89WLU0EmFPN5ejRKdqmZJcOSVd/boIhTYCyd7yuWearZEnvzWdPRdbJtnDTIlp1/je3fAcHavXYDMpd5WiQFyI7aS00xR+uC2jgCxQ+kHMob65KXxuVVmonQG9oUaxTdL4fHTbCEfTjb7wnxyDhAte8BFq+FjoS2sb2k4Ij1/Fc2h3ffcJsPGDLRSvKshqqMi9sVJvc6AvHa9IeH3ajS2/JkiJcokGcxa6OgHu2UyHPynEp96Jr/QYE6jMtazWczKeubG+gaqeXbFuH6XiIHcnWsEg7AI0mxv+A6pI8wMUeAPLWmxoMMi6+CtXJob40phzyO+Rntv+0Wn9hpRrrWpDmkHUBXdZ6h+jnC1ixXmaqjhoq8XNRosWnr1ik=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
