---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCIl6NiyusR6p2rRIRmelLeGqgGGDOFfUDMSQSciTClUPAUP4IJhy523bRsMuqCODpXDLkFPHi2Cjf+wXmC171JH2aQUH8inbezTjZFpPUlnDHbvuE6gG20HpaJe/LdO1OzS7wx12FRkp1qGpbPobGifuJVkPgXNuF429PeTtUaD4oQznhl5kS4YHmOysi64qfYFKTFupjGap9QKZlOvmQQnB0XNd44ml0KZeTpvaSN6c7lIQm8J9Nuk+HVl4x0EpDAeP9u5AZG3RqqGvlVrCOzOw0NPgMzqsDW0pgaD81mURj3AuEAX5rYsBZDvFcZyeNh7cGPTzXioTTPVnjfYWVjm1qQDonp2bffxTInb86L8oB9mK++Nzgkh5KATHi6KafK8Aug7DVGTu4tan14/A90dTbxMHoJIZWaHOjj9pIqxLIc1CKfc5bxpryrp7eNnpGovnshwbrpyJN6HZSDriev3MDYDhgb214M5KBf7qBsy3UmFxevqd55vcQ+NkR4lhXfNkQ4/CT3RnoVd3G7R//Db5gsWo36V/aXOjhIlca2B+3m4RAeHVfYdfmeNhBzAOL32MIko+adcGiLCQQwTtKydzbAeLtJvJ2cDsOFnUwChFIVrYJe8ZclcMH6//F6ADFRurb5ZswY5xBMCZ81e4xYmnU06mxDneQq1I98NTQD7hwDTn2IKJCzGyVF2quxl1qm8KlKglq2MNi06fnbuDKMpTJC55Z9aFiaQXP37OhzV9VVIgQenW8Rvy7LQPnm5ikE60JnCBrFIk+r9cIfttdk4FQz89KDR95V0+ZP1ApNCzC8Ifdz9Yxxm2jtjMaQ4GuPFLIhT90QlD5EwhBtiWI8Tr9lw6eg74E3I8PfYfPTiMt/NV6jIcHuIBBOBUTljVZxWb1lOJXSf4QgryLYu9KifLUqLPffwmtiZAVz1qOfBqosPMhxEbVCAR4JtuDDGMBCfCDgoYCRrUCCHxvFKwcxlr0hAJ8=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
