---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBM5811WbfnAgVegmYwFomntpSsp7qTQ9X+/FYT8VEBigRYr2Lucg1mDJiB0+6UmKFcOkQ9AaUEFmUYlEHtzXGBalKlqCcglpFoVrsFJMsMswW60CjyIiuWs2ljJZkwE7IZ40fTMtx3WMpW7Xug/i37spDyODHUa0p+uiOOT1Jm2+e7+KWkw5YcmZq8feN0/0wcKLRYGPNchdAe9REtweOZHH/ncjrJ8l2hgopm+fD2Q7587SE02Doi3I146KHC59qp+QOuwyg2OemRxPQB2D4TFiPJAggT83CkstL7DazbuTitXxvGLvIF1MhsD6Rf7SKjgpySEUZkXQCdZUbDtsv8dA39ShYFSoWrJBPod2er1TdXvsYHNYSqQUteY1+F0pO3Oa8vDl2Q378IOMDSR3nyo27g9HlLol5VEvZcjtTgLa0LpoF9muYHnzKFQn48xo/npFAdVT7y9duKYUH5YHm7dYqjh5a4ELWL2HkiKLT5MKCzZyfkXbVAkg12QQxvMFbg2lqtJ/GcEaqOMPn+OvJs+eVW6g34KhRMq7wH/NioFByGN1MEnxx41izPAVDit0A1NXrAhrJHnwc0zMsEd7Mg7FM/bCEIR48zTnAEq/z5lZDLbWLLjD4aHr39j5f5LXNMvKTliPW8BuF+QACO8QfcfN9ixqiNLAWZuxUHFuq2i207uxk1VxYl7WEhcdh3HfNJKW3GJPoLIMKN5d0QwdB1Yk+Kk7Y1mIBUcTMf9lsVJRTrRcZrsv/kzEwal6vkj2nzIyppiWZlXBne1vt4DUiMjOdeRfkp90byhw/D7deo8OI+8bIN3u2ENwt9jVZl21i2dE1lnvhauA6H3Ov4qtBqRi9Yd7satfl6oMJEZ1lZay5KVx6VtGUYUUt29OcE8wKqeQrpWFGP4PZpxtGcRxyS2swqqSX+tqQ0vFLZrzODToEQQmCVLMCwweY5ZHn4FGLkmnE8WhZl6sTMBJCxtacrqvvSkbQ=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
