---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAX0n99js+yo6Mb4PsNnuiU2M5XDIFhplXgZejgeZRFmYMyLOW6NZ4jbDoPpkmF/PKZoqk97X0D77wjSpy4/IiPQ0UTdcNoZ3Wu4KkgYlkDzQcEv6mXTV3BZK+bQ6lrU2gjBLJmSnoHutlHxp0CKQUr9VPbYH4lCnhIAkNwrTl+mmf8gOZtlVPTUUIHrHwllyGH1M5Gq6wjZXZdxYuLZsquCn/BIk8ASKaP6m+9IvFzc7d4Tw8l0VNvVz7wesR7nO60gUWva+GjcHDbtULqjQqluMMiTIjt/6+4Ze42u0FllTmrgf/3OirOnxxYiLYpowd4F3q36S4M1CBsp5LL+HcUVjMH7UanGJHRlVysdyFmqaqgDABnvhkIL12HnRoxW3KcFspfxI/aSFnxw/JocQz+Db1i+OEn8QxOOtC1hOKhp7YVNfNpeN0y6BrR0/m6naGlAqehCQeE/RUuNsedXy2Doy3wU7RS5AWnG4u5SwBtPPO7zwGRUYlnWs0HNGAZ4znWjiB/nQaYfISToI1Xtju+AdiVWCTAUY43hggz6ixn8yD1uzjg9WolO8rlXWfZjK9UDJoUcpdgNvF1KIBnCGsVUeeM6VgxgvCo/9d18vpIWyBlkXLkke0SEgmQRZ6kMJUwRUGO3aK3Ri+rX7nQCuXHBeXWunanmHr9Ig4jHm4abeqbibpAH2gC57QWpbXxIDjePBeg1tUmxX5cVr5HD6Ay8Jmya5tTA9kPXvS/j1HMK0T9MZQ0PnZoZAmLDtbd5+RaNHmrdh3qr9Vy2ovEZ2gj8hEHEZvrdQCbVXlkPjMHOWXwyaSEoJQFaHqkxvbeSmTJOajNhI6VkSrNfH8tEnhXrOGUNqwraK03LnXfBm+HCNVki1jtxIaKY6GqVc5ykl9ZEQKlTZiAS0qRqlqG642PNoXCy5LNqWIHO4mMsXgEI6tXv7WhY7ZRTo/+wnCxMKek0BCb0XwvE4LswUi7tzXe/bEicpA=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
