---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAvw5RWvS7QyXwMTvE5DCgzbZPSzh0ST6HkmgwZmUnYLdsC4uf1SHCOQ6jjKZtpV1Iog0npx//5lebia9GSUqsYJ1Tfpv6ipjNi9K5T+Wrs2eF+FpmCkoVSMeZK+DmTvjHXFe5+94GO1cRrR4OY5TBPk0DutwdzHq5sqNmIUy7h0VHf0O59IlVRQ+XIG1S29gyHwn8ts3YUIyx2oWAgTXVIIAFLUEDEEjWZ6x6T9fKXj1r7CZ70CpIB5X/Fg2/wkwvV03PhtmCDnbb9eedBX9PztoeUnhLsX2qjCfRJVFIyjrTP4kAuq+37qirHbaYewLEZ7JbICe+1plMNFHqIJa7+jyeULQJgAcn2Co1JDsRtk+o8ef3jaN93mhhAPyUfJs/9hFo1/F+EV61MMHZ/XBweL+Ar/YOZNAsKOE7hoP4Y0neSoSTt0PnG9ASjPVL/9R+suvOiAvhhjaVq8ZLS+RzAIyLs1hCoNdEDXRGbaU2AMhuuxvR0KDwkj0OslNoz1y4a4QyDmpUdjaAURNL2hnQM+l+C0gjAw6TlFnkbQT0r131RkhQ6pN/Z1k17nD9ckI/1RnPQWVykA6n+mn4cKAZraZm64jZTha3ycSIGqt1+vPzqcJm9hbTtGA99aGxC5YLyJwi1NM3kWZUtsxrgIODFmNVv/50DUWnWE6J2KRe63Pk+tkmv6Z/NWuTkS7YmhRma6z7qbkmQl1uHfwMjlsm7wkOPq4lZG0D+FmwSjhKQijKaAWgdNDYQ7J080CykvQUWsd5s0kQgdDYUW6sKaq8SG5uNGg07YPTIRdCpY3dYeIiK7JRimqX9qSmQbrrOuRdthPTIe8do56J9hg/lab1YnavfSd+xQGAYTsOtxtKlomFFojww5RswpMiY6ITZwhaQKrjRJAzTMdZ33Rm86xUjdIMVJLKHYeijTSdfdUOfuUJ80K4RuxsghH6icin0W6PyYFVWA8Xwc8U16+6MMEbkJzqzQxI=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
