---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAPaQH5C00zF1tVl1f5eHMTotDnDbcXrbl3pYPlrUCYaKroIIz5pUVESnT4du9Z3VUMvTQkqw3JCXjtp0goVMkQPGQYRkEpUKsGVbD3UpN/DEvLkljgugUfzg9Vgb6oXlARomm2bEAyY/xdoclhQWnV0AslsZ4cR4LsEiJk5uuzlHHThRYj0nF7sybtuAkaZSHVkkGZNsNqBQsUEaZWGy/rK+2yRwgXAD6/kTYAEVva7BSMf85odmX6yUjGmcsH/6mlTYCNWvjGYMDG0wFwXkkj2zk2l/zrJdIBJ00rX8uObIIla6nRRvjmvCrEScioqhctJ1zhK/0LpDIXFpY8kr92IxKs54ryFI/zbv6Yzov2+XvkXi2apjWyzG89XUaK26RUy99gK3i+9LcIVeQxshneVbWA33prnN3/YWiIclhH/NVJOUYZ6gTPIG4SD6ls5dsuxUfcMi//wr8WIG3e7DTretVRAyRpDjafGVRHKvOpL42Jgz9hOaz4wgiRaTBb0rA5LFKKjeMMOBF5VlIW73pQXiZyEEjFOaf1TJ5+CK2GZCZP0Sg/yHVaSU4Idlfie+vmLC0kLq03+tSJEbIq18ZrPXloyA/Ao8ZKqbV7rCSwwoX/LG1ucdEfDIjPBqLf1UcvsE85GDtBXqGKSxEaG19Fw/JcdXGgF5g7a61YMUP2YRal/bfhZ6iZV1MCuijkDw/8lLR69yUAf9Vu3sP4kbcHGObSdeQPxhozN6EfDhAANpou9XOJttPwOaM2ywfPMVc4SsUV1cfnPuEAMO6KHDqoM0XsD1gASpIwXuhcy8AHA2xUkLtih9FeJktEP9WFENTTFWN9b/Q2ADbHWNFE/gY5U9jL9kQ5psDl/XvCNGfftQlVw9gyci+YXYmWJq1dHM4fjwsvH9JiWofYpqH6bLe/lzPuRvtAOiOLaylyxqOm1S7KpXdGkgANXLybpuzx2cOtOm9sCxB6mVyIKr7tSJFZp9C50dQ=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
