---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBxIB08yQAjmuaX2LlzZC08bgeJ+M/oW6djlh5uI/Snpe1uCcaPVvLpjJykNxcnowFpu0Hvu9R59+d+5rDr70GfS6dFrrRp8X/TuCAvzChRAPaT3kS52hEfvjnZlahXSE6XrSOHnQvmmh/Nh+SuxczmM0EUQjko77/r26LF0H+jGhjj0dV3b4AesWdAbpUaR15ORrH69ICRwWVY6UFwxw/HTkYeUG1JApbYP2LrbbDSqFIjJ2/hTgq+8qc1RrOkMHceYWZZ2eNOVzJyc0wcTm3nQfhAhRqlNHNY6bIL9qN2EY3DldGFRW1qVQ0Yj/CkuYMRHqbq4RlQRGU9ZqZQiioVNIJF2NX1ikbp6x0FnD3fuyn1BoJW7/YgOh8pSlekt4yF8yt402UuEnt17v3R0L/fCXdXhXnjXcHOyyVLhbOghXEj4IBUBLpCNf9pXkXEmTBApowJwGqxYpKH8bwpIZp8xeHw0c51vU3UByyJyLDTGnPPP+s6Qj3WzBv7+L0j8YZpfZXoxYlFvT4D7qFFyIyTQv1mV3ZLaxqzNyGKcfDOG60arxAhIcQiLoBr/zevQrzbbjfbulLScUqvhRwWOFgG8ncXRRUKRcWrgT8VQqSBUym5a9gKNO48L7RoEGZrIg3sHd6IPPl9W4eCJMEKOIaV864OSp7rbLJ7VHc9NpwrseCa7FwrHdCe28vNtdHZxf/qe+q9+CoHoOPg40RRSGnaFXcMvscWvrtpRT/IldHhx/x9+bnkwiwuQdAYV3oXpcZNKRq1Ne9PQZVqTRyKVfZdZ0qEbRw8HGQtFHu6pc8rnwgsWw5na2sfW9cPH71H+jLuWsfvEPHpXlrqIdPv/oTE2I7IJ4KFZs99uBb0QkzXQAaD94OnuGIfxAU1+nvTsg5vJrBcWG9qLCNbDnKIEsyL8uFELv8ZarI4TH3nm5anyfwYsmv4Yv+PoSftrYkDdiTyAEeObQQy57ih+pTXNIpccGLcvAs=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
