---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBSTBYeZPj9CfFQNeuduMsmhzTifnKQwmVqM3h+PCcewet+JisVKOtf2iSTcptueB8GZ1gy25+YIpPgEr7VdjSF+ruua7Nsy7Wwdo0MF4A1a8uGWYd/tufbz0xqrs8b/AVg+amxj7R48BX+v0D/o1y2NhzUWxkOlbEy7V8t/E9UhVpEemrw5DE36Rvy9jUpIGWrllSPHPT4ya0gQ8KJd0qMZjbpkPr8olgKoGhGphAmeEDFEFdocvE6cjkgjwaUJGvhmcUGoocEa3/FqY0qGczO9NKcotVOpdys9iuj6hI4zE9Dh3q0FvRp+uzBnj2hedQiaQ+G9dn4ICtDvoBJV7fXFiwO8GGkMgJiZ0qzQE9PmvVZVYBf5ByFalxCzN1sZxzVzlyPkZUd9cQi5deaL5vYi1kkl44kPhhuTfc0Z8UDoj6r5L8AeCq1m/EVsIeen693gBsCDjRvKiEuSYd1AJKqeOvncislsn70bB5WMkUT++7223zAvtQYQqfHtXUXXT8Gyw4M5qHOfLRwvPWUbvgvRxV4fRUVaPz6BZGz6Tj8s1LpFDHtkdB5Tbt8wZw87D/mD74mbM8J2oyCW4CSjr48gfLryyn7T18ysqF009kyY/R4HCpQO8lKdC4KTHOEzZX/qq3ARteJAJF5ZbSKUTDqatHSY5fxpJx+L6XxE6uQb7upx4z9DNzGAMTB2vDazbLt+x7TOQLu5mkbQtJea1atFrNHPpNRleOYWG4W38uspEFD+ExBcalLzXzaAeupJKn5BCUNNoZ7cidiGfGUqtE6Anm5YR4D2IBG4Uvh4iFuSnFVST6n4f5xhgJuk+3SamXEVIJnkbi9/TTSHDcpV4Xpmj8KmV+kQTJsKPh4DZZVJJvngFLvDp1kxK/Z3HgJlxVG63/YW4us5xRjS09HYFI95watKZY54KK7AoA9jdAYSXj1QBJT8iQbLLfY9EQ78zCwZ5aScqZ/48+RNUpnLGLXnGeVYGc=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
