---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCJHtTXvUlx9LMRh1XWqs6qndS7ENkZWQgJx10Rf0qJa7fLMtNXQ+TgaTytpVtpu7FjF30JPamoaCu2rZWBO+BtwH2KupQftMaL6FhOBhaADwquQ5phfzpn23aX2JP68+9Sxj6C8ovypdaCMZmHl6XvFs4dYnB21KUAtG+I2bP/jfugv8UCtKMkSWARxxsxGfSYIlHwWVFmbcESIwtyC6CnelhlLKrvYWiiKggFRkdwt3FxCmtdlorKESUhvPm4D4+ObI2wqkD0pFXBzwyzCaVrIrLLv6uU0TdN9ZEoRJ3hP8K5R7QSSJpLL2Cse7Vp88aY1UwEMgPDxWAyZ4we01Wf9rbiustfRylYSpc/RXzlQBeTH7Ft5rGl4HjGe1Fyn8l2zD7ATkdMMliw5nvgTFaEM//R8k6nVIQqj9YfP8EdUvR0K7SkzN1nz7AtML74mX2KH05JfHc9438SQbk7T5JL92Eltv+qLytMNoMt5UcuK9dtNfXvXAYxNfJo4slxcTczYwhaGlC0JfEjjrnDCOHmYr/qJ+0QOSJrkw3p8xjHdN9YJGig4Few1jEB0QR7r5Q5BwcunCPgKv+lZBMqjiG7+tKaUgOjcfe67Jz1HtvDHKn07lgYOEccnwHhg6W4BCJPzMVzBM8t9vvWMoQaMmI140PV8YMhFzE2Jia7VW0T2tGZ9LdGKdUT9RPJsYR5tOy38xkOcs+pumXXmG32PtB0PlrUdnsoJCuh167yv5g4dq9I5dMWUc7fIg9rFKMJm8XdkhkCEjA9Yn2fV0Pydcbcipi+rL6S49dWSREMAC7nz1LDkjgfBgexHwUKrukENJJSLKYGK7DOf0WPWhSnoIQJEMWLJSBylixyGsuyVWoCWyhg9e02aHoznH9joF8o8Pu1ej111Z4lFa8Ui44ve45fAVv940TkDu1EoGWcPllH4m3nFfUyiiHWmoarNSektxp1TcxHkVFAbDJIjtvUMAv+0/8xATA=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
