---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBlETe+ZdF/1SbF88OSwBi8IxQhEgae5JbG9qQKoXhn2pL+AYbV/vRujNgO6Qm1w/P3P8qbDbzUVzpT/GL+gMfimsE0GkryA7RNvI6gQje/h3/GoAZ951StEy1XSjTRLfjtas5COm+p0NbM396TUbXLDII16xaQ6Lcz4P3+pu1WtVMtopjQqjB/jye7G7dOwJjN9+FoNzolFJnYpGY5KqbNJZ3wzeI8VvaNj2nnIbNV38enab99dTccZCrLpVuf/W8u+2FbgKxnauCxCGmo9z1PUczRvJ+L8rRo9JB7nXvtibGKNS1yJnzBafh8cGU+gmqCPUNKD9oDhlRtsvLLTZMjdRlUMz2GNS++hQrLZ/Ecij2yPo/lbQ2KmIWh8A6RhzllR2qvtxhVvNVU2Owq3cOmEbeT2LPbZ9qwPHS7qjEdDkGyT109GIbFSDfSmOeqE9yVVYOphQTzeeocBfgmJmHrF/h6NgdpUwjLG57B7Mf/kpET6Mmxa9AIzTFgPOHOlSrzOhJQovuASA7/bI7vCGIraOxvrg+pY+fJ3OLj7qAJccK01jk+Pql4o/ohIzwQ2kZMGz6DBE1WtrjnbCd3Yt1paBtNiu12e9FKh4XnqIbp69mdMvunOXBE3baD0gQmi4nnomklDBqDeizFzPmzoNJc9vNysyfeKcoBDjyB7CY0rYnPp6TmZjEsjoEQk+T2DNvtTApBEGR2sgDQqxVYOXQ/R3QA9AxFY7uIfg91GUtUON7sIYQQQUHXhMKy+n14jFeFKcl2Joivzkx+UvyoJMI+8LAZJ7saanv3wCtm3K3hOgQjd8MDNElUjy6jAxosA9Vagihvmgq9sXlrJM5eMZ3V2UChsqvARNFfHIv5mO3+hKs1zrBcH6ihpOLzJYtel1txGzx3Ow3w5jmoRlrL6QmKZZ9tf68Fm/dxL+dgu5eWUj2dHvl7jHvnsxIqnJ7KuQq1RE688bvRtyFZ3NoVwVsZcjDP3pk=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
