---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAw3nsxErD7w1SDU189abpF3w8IohhBK36c7e+abFlzrqqyLHkoBgpoAyyAfQPiZvke/goCwVdVjX0zhjsZT9hBRDEge+wOvGmrHOf8z4cJ7r+lQTmWBZab0SJM12CRqGSSne7ysniU65l1YsattVO4azPAHJqwwdCJeLLVggvHaCnKd/mMGqlxfSSEGrGHt/Pad+p7GDeqlETQqmuHI2XY9O8WW1UzHQwk87S7oktEWM+6Fkjt7DOcULgso/pUEAZeu7LrWTDsCjjZwtOJI042uRR4d6YKxTCMMF05Il2nbW47yy3RU+iiCkNqS4AaYozElNCQPkhAf8ZnVhmtrWh9svpJSouN8U2XlfE+whW7WeISbAEu4+OlT5UclwAxtEEKF0FPyK6QOB7jVqGOQyB7ar0hOCaZLxqRK3aQL2e0NLTPKrRM3tfPtoOmSRV14u91anZMRw40l1bghQsrOJjIMesQ+qpCfOx+rguprSafoHy4FTK/fQ1c51spYd5EqmTmL6q0y5p6pmdzB31V/wL1nMkgF0/ZposoJa/ZlVN1Eoq3T20vIkfsfPw+df2oCBqGYmG9wcUvC+ciqliPKxP634EDkUZHfhHjbeFwJGY54z2d47/LiDKfkmxgnpE3zh7bTu3IXyEhurB8h1fCZWhSIBQ4F4OG7jwWMqqO8zNAS6y6MdcOyZfLp+823xPkT3EC3x9cHk0Q92qICRPbCWNW6Ni7p8F/RXNg9HLT8qVRGLA7TYwulFTzgwhQlMwBEWuDkn428aBXKou5UPicqMxz5gkCuWdDFBOneoWr8Tnixwm1kbtD20JxgZRnPsk54t/+jAZYcFMBHglOR6YRUk2nTELr3O4pNyMR7pI79cwUyrjADtGbFO+NN3XCNXG7j9HDPLHzoo/+qX8SudjHLTv7ZX3DqAttGLGGChxN4e5Ahpc9I6uWpPEF0A3g2M/w5VF5DxMW6oqUDrONp1NoeOi0BX4cNt0=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
