---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAqNMsy0AutHoxUzK0zwhHDCu+eoU2xaOJvDtFoyGVeRx0axDN2ntdxzMJAYy4vsK5a3Yd9w39IoRWS/phczqEjnQrQfVN8LfXBBOyTJJB3bOt7dLUhKxgZ8UbfjlulmTt7hq5RtF8S59THlXN68Y0NpWQSia5N7snccIcllW7vWpjD9wX9CYyQv6Bi9NHb041YHo4zIZU5bGB+O8XeqG6LUyBX7+Zwm4zBlLGprdHHF+3M8mWwTeEoI5CRDntVpLWTEJ0Z3b04IuBHGpisPcdqFJN2Mr3QC8wgD9rV+Qjb04s6L51IYCaZOO4M5mKJ3HNZ1dW4XJ6DVRH4M/ngMYoyKXcR1ClKTftQTWksyC8IOjzoFgyCmsq67qQfvSjglyLCBbxbE+/GcBn2N/5qLHi1khYdWqagvZJtEJjDHx6yLhY28AnOQw6pI0lR+nu6dxXan98KFYyyeVwTRdDcCYYfedwZ8vzelQ+4OnJwS8SiYzGjy0ZpmifYvm0ZuK1gWmCg1hs2sK+Tg7SYVDla3zI57wmfujK9sXkIQejdtG5qBaEHTW/KCXFAIwOVQv+Wn72RI3jkrXUgxGmxkqe2Dx1meKXIwtMtmU4oqEF7NJWdMsw7dkv2UHVEpipEglOX7aZax2sULs+k0s/DYLTrmMVsCPhna+hAzdci8/MRHg2ZCRzhsxB6FH+xKKFCSD7t374ok5pnzD3wS3DSIcaHxnU2F8M5vneZfWngeAcdOqqgMjnm65b0Bf12wkPhaO1ISmsBkrXv0fXicCIt7NrEXyqdlaByuPC0ZYwgCElKXVLDE7JootOiXZ1S1V+k8jDvQAh1TMd6PmHc+i2DBHGUvrmd6HtQRiOY+blLchHc7T/OqaBDROIf6U6S3PD4WM5zUgIu0aYZZb0Y8DvIu/kyVn1qw2d4pumb4Rems1G43brhOkuxeYwzPWHIQSzcWYid4HzlBKbZEbXB3VunzI9QjELqC9qIsws=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
