---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBVYO2zzuwHYAmRe1B2qU9XyiML94Hqm64xBKuX+hojce/FD49EUJA2iS29WKsWfMbrkI26wzttkPNrW/aKxtpZoYkoobITlMatjjqLg5dbknF6Ei9lK+6Obco/D3j/1Vbi8CZBraqZL0e7GCPUKTjNOsIiwNpkKZqvRPmmLOSwWLaTY6BoyPad3tmJXgPsjmJe48zXPpmiD+ZO9d/nag32N0xjng+DqUXDEAW6dqJrH4O4NHDbOTm/WZqtdtWA+kd2799T3kga7c8vXN5RGXfV0+w3T/8ObUT+mriMgXbjTXtGl7w0ZERNWxp+zyfBK2lkT9KX0l6UVefaadyjxDr6RkHS6Eg4wQaOavO83Ae0zSnqxUomKf3EwVJ9vUsZjiwh43NyeOTg1Rl6rmi7/mdtv4QNfDCQ8LdD1VR8dD3/V0sal8ztcpRokyfTqvB9UH5J6OHMXvoKLKu0pwHtWIVa2Lv4FaA4W5chAp6+KDIlSAH4d2+dljfajBcpNDYaqsuMh8Hy8WjBOUk98cVZK0MSrmmzi9UzpJ3T4yxty9OojSnBcRhI/1EYhfQgl1idFUYCblUQdE0eCM2BkDqqHNbS2yyONE30X6jS/hNywat2Ca1cEdpcGcN/w0tsWIENuSU0w0LslDqskydnN/owcwO09/MaW9nJljp54hQR/K1cf2h7smTO70+0r726DMJeLA0L+L+CfS1hSvjf76IgLUUTB+DZlLBeHlHqN4wW+xT1Vb4PTwmSoI2u90UuTUaZfCaOQ7UEjQlyRF/Lm4lShpuwd9WFXLNFJshCzYtm0/ngAhluO+zcTgM2iO1NmkC0AL/106BvezDE/xfVEqd6CH0i+pCur7EGEyvlO/RgK7/bcmT00jt4vDp5u/6GVucHYvMT3dvcOXg7ohOCp8BErBZhB8xIBiawAOZrcwZXray2Y+AWkAVYxJWmX2wpUw1HhQuc9T6d20N2YKkijjj2i77IL37kmTY=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
