---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgA8w5Oz+/kUlobSs2xT4IqjBoQRfqFYUjP5d6KC8CDoBvjhdYgtOFgWVBTXYE4rGBYy0HM0i95Pv4GIssRzkleXvvggvlJduSwR62N2ZSQDhp/Agb5Kvggr5teKfIT/ZTue5CeqlGcxI+tM0PiKNza+EKC4GUKYCJCJg7d+IjLObP0rwwcpmPdm2rPvhBsS7cw+cIpw1rTmuWK5jaYIZRN2yEZot3iEsYOuOXFV+4tdnFl4np1XV6zPk7Wa9hxGwxew+djfGfDueFF6MpDoOzvehf1+yBfsXtLNA0s8cU/IfK5GOXDoixP6aANx1LVRzyE5wwkNNAKKc8yBJ0VZSaYYmJluhEnHskz9vWVVXP56i/4ylnqSQJ6uBjpzNgA5irySKQ+SpTTtPyOQF/QuDQQNeggXicPiOCsZNWqq4/G9m3GwF3KSTFkGOjaLc488T/Nw5xqTB85C1k+fPdiM5vf/cT5e+HPSJYJsyObUYVhYWqx4wS8L93H0G4WBic8Jj5yYh7xGB5VcjBdiuR777558k/OJx0jaSok92s3ybKOxd2saio2iiAKLeDmKXYnkcB7Dbtrsp2vyxd90c3Fr/73n6tXpBhsP2cvuIIrlgHtmngcdSsmF32W0hKt4LC/HtTa51GuC1h4efeZ85sGOwnsy9F7u1Smrlqu0s4WIXgnglBjPdGH7twK5lLm8CX0XXDmRzG2SR3S5O9wUOtOba4J8UYpjM90daQzltN/ZzbYEi0Z3kyPk/nqfim/Is+y35wdpJiSlFQEFHmkFWwBVERgLCuimzSLvuvu8xbww4Byf6soLYEP7DJzy9f9A9Red29/HAULOYhYY0Si9++ybgem8WoBV4UYcAKdHln7Pt2W1lZ9d+U0Odg+vUcV04ujbtSrfxTjoZ17xvLTVl2t4Xr04p53bzbEVy4O+YvEzRBasZ+2cqLs/l5c2xNtpUrF5HejHR9KTgqwYPdRbX8WPWrxOkq2muPc=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
