---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAQylJYDjOutwyrlpox8+g2Lqm0eAuofZC8X7L9HrXAq+whkOB+qPJXHoqIqMb4EKkkzc1LpFdUjw6yjw3MJDMSV7i4rWzVk9CHtA2OkMU+Sx/znhUScCAApT0MR6Jh9di6DGX8vl7Y9ahKg6E6iaax1SgK52x4cBAFKmMr8GFJNayDCxd1o2Em82dArRELhWGOCg7hmIbaiFPwYdoGxwArwrnnK5RyzbpAbLeLYCJdGfkmj3A2Cr3/l1m3quxnptAiMu6mryaDZYVOp580WWFXJM5YdyTgFhRmUSGYO95gUA28IfPEy9KtqImKMrYKsJeTerZuTQhAtUgG26TzmoaxTtmuQdgHXid2429xKU5JEBdXoX7tGQ2Zq2ycvTqKdzIoBYcK0h7g08nVDjRK2HCmuwZaNea+3+G05TjSaGYWYhX6biO6tNXA2pMaKBxTYUyClmDaLnAExeC3fFR+pVcDRo8YlFAvGIZ8iMvL86Ht8a9Bfx7wtUKdFUBF7ySut282ftkIEzivbsPdeP1idbvLuWBBnyX/r+K5YoR0DLgLX77nIDZdA9AapyO70jysWEFO97sxChoW1rudIiUh9lv/PzlZNAJALre1xi0ialdqRkO280WLdpsTpWRzRadn9AfIWn+U/fis7EJfGoF29u0E6Kcm58FjIL9lb3kB6+el9+xLPT/iYjgd2ORdDK3uzZLiQbQQv4q3kl+bLSNgo9Bnml7CkWEEoAe5JapUK7+3t6AoykAl24BaTV3WdrIEhjD5qWTh35sLLfEzChWbc6ruaHrqsNM8z5DZ+YPa3k1X5KRlDGyGHIQbA25cCevKKteiBy4uw6n/fq2tM7AZj5kUWrBfcYQXTflv/YGviiReVquKUxul1EpS3e4EB98ljBHmvqGyW0ueDyhJEQ5c9AmCJRxEOdjsFOzJA7FE2Q5t1cjUAwT1U1OpZrWR7JmnvPSFBBdg+2N2iynwWBxWbJNzmo18Yw4=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
