---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAOnovdtxOwT8T/liCPYpaeWfssxxU7HLR86OKfh8d4qtEegIBqw9oqkLKOL9vKMqkNFBK81qHtA149hZsV/6/tAJFbbjDD7ddwoQCmmkfm9BCwMgyzyGjvhnWCuEoFiJ+oJB3lFH0Bp/hspB9//+06bbQ91Gn1nvw59myld8e34YH2WhfJJWMEav5n6IpXv/ol+Ib0/hLFwjYBOn9zle0S/tYEgJeChPbvC8yRRXsBSR8SwSF61/dFluCAUulbep9YG4sCSrtqLOrhSdV7LixRKQBxYv5ykFYcK9bjmbvpLFl4JH0g7r1elkfhJ7Pwie/DnAfOxAaOJOfkMEZFezAddan+TRYYeXK4wvlGIfwqSUN4CTnmNbJvqpiS084dyopug2ITOQbRE+SD6gNpzK12TFXmowcZKa769dwfdTmu5FPEhQNJgBDEf/QTa7Tdt3ABjcQaA+ceqrem+vA29SkbZxqN9tMYCRExX0dyzF4YxZ9PP7kr020mhnCDWZRxjwrnV3EWB1eO9kBN+FqCFq1rLmSyruobsgEQAndOm9p3pQCtaeKaQykBftFuTKnI4oFcJyY3Wc4kLSrpq4EJd99VK65Agkaz9xzp/qSu01cMID4staN7pK8N2VGRHe9bZtguarpJvk075xJ6SLDvDItqCdrEkemRXbHv1t+Gv27OFfiE+6pA0lOcsYXbGjMuUZo4pHnt0W8XhLXAdVAScXDZN0IuLLj9VptETI/MbQ1cZg2TLdJdzJb0JDudIAODhuPiPr0B4PqbKsClt728w6t66kYhzoVMj4g6W3OVOQtBHWlyXZGOnh0XpRfhNOlcXEa6lGbeCth0QYnswQXqoEQCg6YKPAVWOf/h8SlUoSUPQrOIBTafbEsduf6J83BgILlAhHiKBQ57T49ApiNvWgGJDa2mfXw9cZ1YCJDLMLUTkUEdoLWznvMf7z7ia7ssWyenW2CBC1W2pNyfMp3+ILFn5EGwuJo=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
