---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBE78XyoUnCzZ4h3Fj8Xb4H7J/4PxzZ7Rz04S6I3zP7c3KGkxIa2KEULq9yxr/Jj+8G0CarU7byF5M+dK/i3KIXik0xsWhkZQ6dmbCUHS3o8ZLgnh8BDakxvKXb9iyqwSgVUbiMFHi1kt9jgrw9rS9LOABmiggiVZfDwBWnBlMkZlCGNxTRCsyjUoKMWeVTFzk9maTwWAkqMJd0ekBnJ0/SJFwhTG8jfQyv8kWfNpXjKmcozijlT/S7aLVlKNljD4N0qLAlXjDuexVwPPAOXxI9f9VXDeBbg34r+VyM56K+rVU+K5EpsHqRiSIZQw1FoOGafUf88zEgCl3DpmdkMqIvLTwnkUYGgshrMoUNfBUs6Y8HELbzsXIbEKw2za5pUXK1P7+5HBqaJSRYFJqjdJiwPi96vMM1HpQyCN3dKsLq6c4V23ENs306ccBAjIDyfNfg6GGE1gLQykrxTk7r+5Zb5PhNocCDw965Zxjnppwnj+jHUF3qLLJcC5kK5VhVCh0B5WPbWmxmEekhXCCeo4h5aFwq1wW7VCYdCxJsOHCsBXj8pk4gFjsEhb0S6j+GfXArOkXbm73bMR/PBhgCjjRYGilF4ychCDuY4XisKhnF16nFavGaxpLnvcHifdBrECQ3hWNyQCFTQj6w+ioKDEUrV6ShNmhtAgyd5WfMxZ85z9bIiUgVQB51HQ8huY7OPb/I+Hp8AVDA+g9frQL9wDAWSUd2G2+uD38JNRq/QRLes/D/CjWVfmuHk7/pw6CNUDrM7JtNPqgvWI5Q6yWegaxtnEGgKXH7qBZCaTzWuVVALoqEGU1UQVCmEQHS0vhNwOwvgnoznvUVC1cH4Y1fQSOApYQ5ws6kXlnYLwCrDPe8HDRT5kSK7w4q6JYzSF1cf0Uni15DFEXskqFXAaZ6n453v0gPxD1vmPJ0Yuo2LTKKnt2U9UUkp0GrzaP0VmChuFsOwtAkfqx1wWQUgxQ1MVcAnveIVCg=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
