---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAggS8+T3og1TMRBDixY7y21NDSL0buHh7C2JfsnLNsrQID6fKutegaVlSjXxJnqIBHUrzXE1l3cn4N5GuSTXdbIQcfzUFJO0YVu+ccK7679UJ+kFsCec2HnfyQMVy++LIVb2wHxl374Kl/uIj1rCpcmpDvKDJAlAGdWl/592HaHn7HqeaB2tImk/NZ4ZfGOhAnrasRPlbF04Xl5WYWoprQAtrfOrM46ryM8lgxphIbiJGd6pXh5tzQ5dhw2clnk0WyqhqbzbbG03QQWs6B8cg+h6YUeUSdWWsKfcuBW54oOAn15FpKEJg3ICDErQTFpHYNymnsLczCt9qHvqOu5TJOOFmTCMCp46KS3Hc0uS3TidCYl1ulAmK7udWxeAUyJuTL/1z6sN+gy1JNTQYhPhfY4NpWrnKm4ZpWbFvqZuji5NRPvoTonC6aaPzsn9+CHAwMhcG534jP+mUVN3es+Jb9qh5DJtE+5H2/6a0X4OYtBCaTP9G9Zuyfxx6RXPJMxDgVEEnXuzBcOC0UpVn5x5wLMaFBqE4KyCbZ8s6gtOZxQyrLIMJN2LP0ZF9Wzrhr1RsxaoWwSVhtUqP2i4gadXXAkcI75N2REizkO4tlfhLJUFyoSR4gS5ErTvUAtodQHdHaU3m9LM7oFhOaI8XCnJ4n0zrBuDwkOYn2FIdZNcI1hfq5owN+pP04HIpseFSBIUM5dDQKPAkRJQrZ+ZsTvKFYUkxToAnFLjvseFmQk6m9YDEH/7EgG/t7ZYqDfTPiIx4BqLGy3p9YPbVzn37zRryevsyTi7RUWga8F+2IEpS8nt5XQf3W31ANjDOis+CJF8+aG8ZQ3mQs3D5rXqQEQQ/gHA3tQUROX5zcL85icE3mQY28HjzYGPOHkZjx3J90aQHdlonRnDdLzWVO8e2TRiy15uFZtbPknEm7QiWD2+f+jflfbdDBQ2Tt/npxQOscHp+9A3QVKH08MLA+IrKPyoxju5/rjcg=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
