---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCGYli1X6Sbq7uzDUGRSfRe2f/s2JAo1F7BkpK3lFjbno8ymDh6x/eXm0DjrHdlXNPlFwzcekV5nA4OX1FceDBV2MkV2yLA2wuIrdCGtcgYM701GtYw9+sfGD6wtCzR+M/fkH37xGEsT9rEvNQ/qsL9j+RIcLnhUzjR9EIYqRsNOMUClH9oFHa+7nL1hStNb3a0DHp3ueJ0eVNGMq9hAaEC3lSrpXHwC+SvP/4HkESJj+mKvR87BefqYgAJBDdQLzMOBpJlA/oNk9dxpCgOJxLFxSVLJdLsgkr0T06hQmvhrf/5k+4XUAvjNDjvtyJrjIIKuLhpR9fn/m9a5ylQS+Y3gtJReMGcnK5OfUGAVvC0rTNpVGR8w1nM/DJyso7TGE5ClDvIXOBRR8WOENdVPRJQ2McCSNB13foz4w0puBe5QZwBhn4eW1bp5FRZcrtODzaKmORtSJMpXpc5KJh1FUcACk+DzkijYnRvhUPAMKPBeKKTm8Bk3wN3pn64og8w5Oh9Ro+7RBz+AZtQo9PxymjYlO1Uaw+wFQ9cGMDL0momV1xZSkJdGTFccpCXkbMmM+MUGf8crW3aQUsWRnrfxzi64roSzM+eDSI5j79lJ/X3LRbg8KI/55H4/wVcvdL6UvBYpYxwrvoqOoCuPblb5gynJWF5Uiw+3rbz93CUR3xe42k9xGTVUzafzzMLdP4BOeb6OYyQT84w0QocM++AhVXlwunRsC2B89KliOrFNFAwCX2Ycv6t9UCy3ZKGWeiKPPAuwLvRXpPj2TK8V+ysMoy+SQ5oTe4phrFf4BLu1Z54lkZ0reTrV2aVBo0fAmal+52yVHzymJC3XFMWt+QOBpF7zbBc875DDrMSEM+rOZ76eIlapEOSjkzj1X1HXtaFAH1PXQ5RUa8olnkUKHdOvu6pO2GRMD3o3yTogIOaZ5Hfz2zqs1610PDXmgex2fdYXE41t7jWLfqp5By4hCmtv2yZ+1fIsQ8=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
