---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCWn2J6RHfHeoKj5FQbaz4mwhJFzCqsUQHIUKGc7Y4W1yhOwims6mPEzolSwVUaHH9pvu6chxla0ME2r0IZYV5/9PoD8/+4T8yj+CTK6ZSaojmIFL0VL0lasnNP3C7mTxM5jXP1SQ02dn2suxmuEtK4pWTZpVEKeDz4SmHJphkhLwgMTqaKEuGp/C6L2RmHOcUiRFavM0/gxJ0QE21dtxoK/ui+STd0/AaCb8plCszRWUf/OYyr6O9hi1NDXVAa4zgd5ubVU+NJRJWpnFOKoe6ycsq9zo96P2CujspSizLgQeDHbT5gduFoBZT6dWZiYHOl8+dRxBEFSIsNAjp1gp52NbVpZJiprlzDgLfggrMrOoBA9+1haQrUe6mu+oKYCj3Y0+iEkd/DDcODlDNWkk6RZqDmfb5FkiV1PI/GmQ82Odepje8lXZxPlZz7JfWkt1mczCZFqwoXgdFgU1om4zwYH787DoyJYvHVMt6/xwV1NCXDjP0TUWldqp7PbDoOC7W1hCldKZrydBuH71f7qnQST6OZKzTUBqD0LKzA6MZP8JfVVOw6nExTnqOID3V08EmMWWujJ29XAIsr+iprFK9QBp5/tGHxPxbt2o2tTBc8GKrKsh1lExSUxWVSyMpwabUe6tR3vYLgF3qc8LkzW8HD5NcoCKj1k1BSvSnquZSgadjjMDlVKZnSrcKEdeaiuy/XwxufEwy+30UEGQmO5pPnXcmvG14W2riL7zs21cvGjz9Ff2hXVPb7cIuLnPPd0rSNT4M1ixujrBAwrmp6MX7GIfBt0kcRH9JK2rHPSEZ2TkuU0kqwpw/a0TqtoAaCo79q+NGwbnrOzpoEa8GtgcUjCosONpWOUzwq0EeAfk5Md9Iat4BH3NH8y3vjfkQw9J/eVdzf3FwPFHSDyNahcYSo1omA+UJ8UGRZwnPB/T+pK0tRak5gQggmmWmv7WmXA2SzEi4vYS+/GVPL/930hByCCsGGH+g=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
