---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBhIyXgQ+cT/tZT+Rn1m0P3WlQUEO2VlwCGUhTeV/ZqNupFeyiICbxoubnM306ITxMsMbMZfqoz1+W/DzuVMYMwGL7Rnb+hh8O6gM+XYGD2OfuNt9vJRkqCHzBQi667in+gBANB3hbE52pUcks5vhspwAAyr9ccCK059SyaSIXT4SEZmmlFlKr6pg/AWviWImB7tRsLEU/+lpHzRtx+AT1PJYAHp57tZkgG8ZbOk9SBbQfhm0cyf6FqFfo5DtbzYIvDVoRZP9s5jRiT7jP/kdbkuAI7aF/EmOFKRW6SY9cyIF1ibY8eBgbi/7pBD0eTPdxTM93ySpQC0rChiZngB4xFsmp45aF1Mu90Z6hP8SzvbDzYLQrCKxM+PMCgiQninwF6GnHpQiN9d0VoX+CanBXjPs8++dmuV4vl2a4G/feJABeOMsue/4R/wV6/SxkMwJQtOL7Emee/djrYod/zqy95KndgQ9ADOGijp39z0sHAgBn92WOYSeze/DN9D+RhnQDnb0ZqqfO7leUk5yNwJBEulIo75Ir1lHZpYyf1RP60drML9BbsctVIjW5uwcz4XxYJWW9K2lpQDaJplDLgZhW/jNRvLMGtK2bJwvjJ9hU43LNmmQTqRjLRgTTwQYgDzdK/sp7ASTLNYijQOAXvIOKj3zZPPniCkeosM673v6GXba2u13wYoyz5FQujTFdmTfRig0quFefqhyAOTNH9yqzvmP9MrICb5Gmn+esuq+bb3w4P+KtFGbeKwBUwILzyxBKZ8b3RkNLu3pWazXM3v0PN+++9Mys9LcDuNR5JXQDsA1oqtrMFrBgWMSFOoyiEUGCI/vQDggsvE5YOQXTg3+kEfOnGHpklO6EywXfF1QEoPWDIPqPOmLJLeBbNF+l4F7Z8nafKSDk69EHE+k4TmPJCBZifIa0YjaY2Hh0eBaYkvO7DhCR6aEGJw9y71VoKzheL6tFMgoFYAD70bSis97IMEdS44OE=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
