---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCIpIB/oc/FG4pZgT4gN6QnMEsJAnfEUq3AIRbUG6BC7Z0FYdMY4Bvyzg76LEhooKLKMZhIAlOtaGR6g7sXQ1vOijeravaTZdMl5sY8oKOVRMY1xf4y2Vd9uYa0XuDMfFy5W/NQgSdy1fHPExyvxAtb0MiprOzBmFHLNC8Lrtu1Ty0/hpY2+REPlRigNzRIo7nbmpVblot1CxatLre3xFG69P92ZGtuQhs/8tYGm/VNkGtCkT5+SqSVoaR/NLGt2rkDHwrjNKrf9v12Yj27yW2aQV5D8hqVWvsZgB56tvbXVrEsHYoaJPYPgZRHXHWHBwXgcvaB4Exv8UgLt+espCUAOsLD7HGQVk/ChIYSQ++NmcJfEoAS4rBZ7SvrVyvaB5gBRvbkF8nBcmq6VwNRfWGDeWQimUbmEQfsRHIJi8ylkqcS85fEZDu4EH2mkJdxYeqnwufSQcLMeMSbxSAl22IvS9gL3eWZ1+59yK/qmDjWbFI1ld7eWCN9LtobSAplFgeXcLbNR/W1W/E+mR+Q+O0NrtLz5aWkR3yqQGHgS/YZyPIc4JgS2EaIvkaQoLOPVCZQmBMG47i1v5gKOGP+UsgzcKSsbs/RlSmOary/GGmw8CSpdSwM9Iobaa2BngAQ7l8gMO4eYurKrhqVnz0wqnpLvNTI+4Iz+doUkM3GUTdKKXxYyWRX+Gj0vI6ov8nia78n6jb92khdoxjoeI5cCz061rb4819R5SNEc9FZx4uYGVPES58rMIese3mArJC3l5JVhBbEp6rTqj885WKH0+SZazNjqYV6yrjvxkcR9OY7QnzKauGN/TZUUrNNsewTaupTFbXiiR6KpNnri1iknsZFLBUqFZbjYr2K/8xxuUzATFYiZEB3y3mnlTqeWM/zpJOPXjkpEhMKheR5DefoVrGeTQ1ToOpupn16GAcyWzj1z4b0dV34GuvFFMcIkSzktqlf0zBPuDEXfELMikALOxhR/5WORgM=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
