---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-creds
  namespace: messageboard-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAPo3hA7+kF9wZGFSw7I+p/d1pcKkF6hMsB2RDY8iZk7Wt8RfEuPIc2r/HrSbAoUf5lSepzAf0WHyujDEqMlqtOEoZSXz55YjUitC+vculwUuy+5STLg+R4d1h8Yt15MivyvuFdQzCHynFZd+cpjWS9ZXF83n7X2GgM+tET22nTYonQaLZeeDKK+RNNSWD/37MmwiaW869OgsZBG1uS2IFsR4yuvh+wnkXMVNl2M88/ZVdHv7BfqfZqLUFE+BRzusXNzoNQJfPLNfMerVjLKw4jqpT/L0/arlqzrilYK1bMHWbTIPq9IAbq79izFMHiuRJIWVyCY/z3dMPaxl6OGOHezBcv6mEoQ90U4YmRZMCcVxxGHjGLCP4hmZWd4l+xJHoF+AsrLWupblYl0NJt/Ud7J62XCY6fbZ3DU67GOjUsdXaSSCxFP2Nrb0GYSM95Y9q52gCtX1Z6/KQ+njOKscxNNTs5DTRgErR7WfSJkNH0dhBx7KsK/WTMeWv25cNgV1b3N7ZhyP0r84q/Zu73PkbZox7p3lI/8EGJwJoLVyVt4BnlPh5sxw+SRQQkWPck63xMCSMzU+htcRiDZNcwVu9FJipcBsTlsf9dQRF5SjbBw0HqkYLd1i+xWIHwyrc6yruN78JKT/sLalW4pyalpOdqzCNSIEQqmjBzblGvj6zyNMHS1ZguYrfvEEFxS06tUk/wZnEi/iiI03oxqGEbsWjpCBvd1DC1NsDgdPzhNw79iGkGrwfmz/LpSBYWHFoJUB6nDxYxcR7RapnXRcT7XZZS+mPc/rylJkV4NTVc/mViumbk5gM94fHN/uobjfxYw3b53OISz2Neg/JhXolMpDEznxbK4S2n4CceWXyDvtIM09Pggz1zDjb8fO+VUEHFn7KgnPxnZiAs2jqIyjo6s/ZWsvu+k3NaCrZEqXNxeS7Zkkg/P4Dx1yNLSagL8UzSUACZ4MmPgR+YpLRo9Kl4oDx+2xJ0TlU=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-creds
      namespace: messageboard-dev
    type: kubernetes.io/dockerconfigjson
