apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
    app.kubernetes.io/instance: my-app
  annotations:
    argocd.argoproj.io/refresh: "hard"
    argocd.argoproj.io/port: "80"
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30081
