apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1  # This can be overridden in overlays
  selector:
    matchLabels:
      app: my-app  # This should be stable (you can choose a general app name)
  template:
    metadata:
      labels:
        app: my-app  # Default label — will be patched in overlays
    spec:
      containers:
        - name: my-app
          image: gitauwairimu/messageboard:latest
          ports:
            - containerPort: 8080
