apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dev-hpa1
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: my-app
  minReplicas: 1
  maxReplicas: 6  # Lower max for dev environment
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70