apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml
- db-config.yaml
- sealed-db-secret.yaml
- postgres.yaml
- postgres-pvc.yaml
# - ingress.yaml

# - https://github.com/prometheus-operator/kube-prometheus?ref=v0.11.0

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: e305785f83a3f0979cc6c2776a22945eeb2afbd2


# - path: patch-deployment.yaml
patches:
- path: patch-service.yaml
- path: patch-rollout.yaml
- path: prometheus-patch.yaml
