apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml
- https://github.com/prometheus-operator/kube-prometheus?ref=v0.11.0

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: 4c969dc49c72e94799d5b949a1a54d0a3d00cbe1


patches:
- path: patch-service.yaml
- path: patch-deployment.yaml
