resources:
- ../../base

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: 344d6e8b174601aab2a08b25e54ff1afdb3023ff

patchesStrategicMerge:
- patch-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
