apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml
- sealed-secret.yaml

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: 38203a3ca096afa3bb94cc9f27b8d0fc80842d5c


patches:
- path: patch-service.yaml
- path: patch-deployment.yaml
