apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml
- db-config.yaml
- sealed-db-secret.yaml
- postgres.yaml
- postgres-pvc.yaml
# - ingress.yaml

# - https://github.com/prometheus-operator/kube-prometheus?ref=v0.11.0

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: d10639919d294bc54c4dec907873dc538df90956


# - path: patch-deployment.yaml
patches:
- path: patch-service.yaml
- path: patch-rollout.yaml
- path: prometheus-patch.yaml
