apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml
# - ingress.yaml

# - https://github.com/prometheus-operator/kube-prometheus?ref=v0.11.0

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: 7c92c45df861ac1b0600fc5ad80ac66934e30f03


# - path: patch-deployment.yaml
patches:
- path: patch-service.yaml
- path: patch-rollout.yaml
- path: prometheus-patch.yaml
