apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: 13f4fddd4d11fb0bbca0366dbe2fca61e25dd4bc

  # - path: patch-deployment.yaml
patches:
- path: patch-rollout.yaml
- path: patch-service.yaml
