apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: 57102d8603829784d83974af63da5b1b0a2e7871

patches:
- path: patch-deployment.yaml
- path: patch-service.yaml
