apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml
# - ingress.yaml

# - https://github.com/prometheus-operator/kube-prometheus?ref=v0.11.0

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: bfb7d4985d74fc5a3097d59279f134e6d7548f41


# - path: patch-deployment.yaml
patches:
- path: patch-service.yaml
- path: patch-rollout.yaml
- path: prometheus-patch.yaml
