apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml
- db-config.yaml
- sealed-db-secret.yaml
- postgres.yaml
- postgres-pvc.yaml
- ingress.yaml
# - hpa.yaml

# - https://github.com/prometheus-operator/kube-prometheus?ref=v0.11.0

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: 160e504d69a6ed37309d8e729223dc5fb9c37c26


# - path: patch-deployment.yaml
patches:
- path: patch-service.yaml
- path: patch-rollout.yaml
- path: prometheus-patch.yaml
- path: hpa-patch.yaml
