apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml
- patch-rollout.yaml

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: 25bf8263fb945f7caca7119256adb06f09dcf007

patches:
  # - path: patch-rollout.yaml
  # - path: patch-deployment.yaml
  - path: patch-service.yaml
