apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messageboard-dev
resources:
- ../../base
- namespace.yaml
- ingress.yaml

# - https://github.com/prometheus-operator/kube-prometheus?ref=v0.11.0

images:
- name: gitauwairimu/messageboard
  newName: gitauwairimu/messageboard
  newTag: d54360cbf54bd168d2c7909876c951875dbdfe72


patches:
- path: patch-service.yaml
- path: patch-deployment.yaml
- path: prometheus-patch.yaml
