apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  ports:
    - name: http  # Required name for port 80
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30081
    - name: https  # Required name for port 443
      port: 443
      targetPort: 8080
      protocol: TCP
      nodePort: 30082
