apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        version: "v1.0.0"  # 🔁 Version label retained
        app.kubernetes.io/instance: my-app
    spec:
      # initContainers:
      #   - name: wait-for-postgres
      #     image: busybox:1.36

      containers:
        - name: my-app
          resources:
            requests:
              cpu: "250m"    # Must match base or be overridden
              memory: "312Mi"
            limits:
              cpu: "300m"
              memory: "424Mi"
          image: gitauwairimu/messageboard:latest 
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: SPRING_DATASOURCE_DRIVER
            - name: SPRING_JPA_PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: SPRING_JPA_PLATFORM
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD

        
