---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCazaiV+QIhTivkTGytDFxEeNWuB4kKxq8edgA41eoOaQf+nkuEolGSLAyTHvM9JywcU45HapKbrlhysnQn58wpbmAoHLwaT59USwqnUN8gxPHqBH+Nhzdh2tdaYxjFw2LC1qoNgvbGGMhuSh1CnVF/Wujcs+Jlxf2NUPrMKIUEQdNyy0Yj0mgrrPOnlRLuQxGACab11bmY1hecfDha7MWDg1IBcHG/1AI1QTXsvo77o5fj4n3cEz5YW5CdcLH2zQ0+6Ymci4V33HdlvmxBnIZQfl4PB4BNnXl06Et1zMRjEaIWW95uZBYO4GmqgeXiex6GrjSX7z6Slq94QUcz0j+YmieABfxzl3MXRD6b00z33KzYGfz4eFc0iOB6RRhNJySuoN8qX5APWZEnjNL6ehz4Qyvh5WT5twSgxRv8QheVxognfQ4gV/LvXyD7IHOjmFZuVpN4siXQlZAxkDFJ+AxWEuhnSFPBO44PQaGO+dTkOi5mAHmSziKkn52rS3EOi1tIX5oLFdTxWZbctHBKTvIHc2+Y14kKbQi5OjG28evEzfOYRnVxXNtUYe40kdP6uGb+SUgZewVxq/Bzy5BhyJ5pQOytu7RRYyxUlnO/EupsCYLfC4KWtr3a0BLBq8sItf1G/7VIJoa/lkfHPqM8BsKnoyXrEouckBy2eJDCpUjDXYxFzNbFlOcmLdvD9lwMna7uA7tQh2N3CmSNpzPAUtU=
    POSTGRES_USER: AgBa7LhyaKK9S0bqnmu5u95veGVstOuS1oNF72xCHujfFibZkqVKlq1fe5BJbQSD+1SxwpkUBfCQ89m7LA1Jr8zjDsBIkeEVfJ/JwBXC4nulDY56jpNdmnw+p3S2gyWcqe7CjHvY3N8kcnr92EbhyEc/12gxdDeaOWQh961gNrS2fGLHHWosH0xE3DsxNHXNbRpdHRjF7B4kSNv62JHzYBnB/HKHnQ74uWTek+WT5lp9ObdqhFBs2e6VDHCzRKl2K8CPusSi1ywJJPwNURhfm6szHGfWILwdSj7Uh1sYWG4NcAiK2JK5CMNvxvJtdhae8F6wXDRZM3MMkgRhMjgn/VIspBh06DDxHqehCfRxUykaNvqUAfRGXxV7WInlV7M8zFhrFx6JXA8LpUMzO9b/pg1mJb0H8hKBSewwH/DJ7gINFg0RAlweGF0alscUHyhN4msytKC3yrWavBTrv5GmIMbRfmt9oh0SSnC44Bvyq6MUCrAQSyKmAhiDValbBkLyC3zSGBePqR2ogcXRoumfQvbhhVp0ARzj3uzQCbEikJci4DcicQFvfdU2FiwN8YI2+ZZn0rpjr5rIFIc7X2Qa4W7KxqQiMJxZd4KCGMyTXhiOw9fw+88L8rmG8Bj7xeKWjL76NPoDsl4qdHCDwT+1ojWj2EDNyK4l5xP4vbOvQStTQsVVp703ujaVAJv3NpucS2X7cJyYzISB
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
