---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAPez/9LgkJz+Ofn2BGVztZ2Nftb/nKwoV7ybrEiv0SIYgXFL7ZtpzYZlyxswvnLMSbgffhfZjyMrpabatICQazvq2aj6fe/fK/EgImKpLWFZSn+BS5oprZPDvZESI+8i5Q7+rUWFD7d8YPSoIppQ8wurL76l7qORlzxPysdp+jfLlQSRNQ9aEPRc1LCuXvy/CauPPGSttA+yO94XWuSx645Mm5JTB/ZUtDLPgRFg2H5Z3kOThKvLFdp2HDgFejZIp+7++IMk4SgiweKTNaVzdC5YK6LnbaqZiovSTRrYw7ft3MhXYYBbpmjfdC6kPIPIveeMyp56zD15gCHyyIvQtbqhwnfKj4ogzhIdlnH2m7iml1hYvwmOtBUHFm0/zgENCyqdwp6wklPHtaybhJzd+aJEstzjrMfrQXRCHY0LP8bxTF/BtLpmHaAT713Ze40JvKU4UbEohzrHwVM8lu7zAB5yd97RCao3uwJdAeq40MK/eTOJDjw1nnQhMT9DnTTBe7rBoFpJvA0/udO8Z5z8jMHuNW7016dcHGxLDWkbXmdWP/+0P8/haKLz+cdgmg84bawuAybl6IUAggk7Mz/dfzvURgdUdXQqn2zHB4ogaNYPrZfIbc0AejG/jZ+0wJBLAFUp5dJRDrHSyBGckq5ePgf+/2gs8Da22rMY6v1kMIgHrwzHXAg6WjHDp571AJhlSQztcv79DcpXBqDw1sEb0=
    POSTGRES_USER: AgAhTIMc0ik8O5k92cCwbA/zp0dKBmQwFY5gcYF1+BWrKLsfNvjqUetTirGelc4Q0yBEcJHetrg7QMxuWgo/XdruDHhSX2qCat0Wns96VsFQyy9Ie5gufFSLTnNvKF+Qyv0JEmYZJakr1Go12dkx/OWc4hwYjHja0tRXVrCWQ/tKaxTKG3elHJ/yugjF8AuLUfpaFv7WfFpqN+sPSP88xn8tXxBbKARfHSv2drjQMug1zbl8KTNRAA2QDkhln2riJE9en7CXE0bJSYw9HBpWY+RZSBt2VKdDRAszAXAQN3Au0f0r5CBxng2IqBPbxRZ293ArVWzz/KNK9NNtkdhIuvopOWL4+FNwWlAKf8locHVluiwjiapHmmP1FeZdQxbwhUSUoVK4gHahnNcGM9UtGfW1gKQ2abjeLPiVlClcbPl63e3vtkme4V2zO3hBlviUm8ZSx6equKC+Yzp2VLOM8jRm0XYD67W+DCjGhnU4SGY5VLcjqZzfk52LRRQEChn8DlRRlvIoxuFGFZyg4xOmgn8iu32bbBhdLZHC1bNVZc4+zzmhC8fExp5S57gu7yo2mO3zGInT0s1HAZB9gCNEE6Y/kHIgdOK04NnosNBYFs8nwG51/0Rk4WwxGTUKUiXKSaFZUSAQTsaz0AOCZhZZmBy4WG1o7BX0DjIfhaTb1pIKpdyZmaC6Vmqd4hbTuxyAWz44KDcFDDe5
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
