---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA1EG3q8gsJ8onje1xee+cToSg+w1rdzZ5r0If9lv4uQH4nHc47MH/cQyckgnSLE4xUnYZ2L1+8TQgCvhYbplvePOoZC8rxRy+Zui+uJZdP5ZVFDMyKw78NlKB2n4puKtLyNn3IZPm2OQ6VkUVzRNCnfI551yE0qgyKkdn+rT0kERYkBPWiIEo220osScatVHbp6PodXqXBOpKgOOnKLR8t+ifa9DvophT3bzYUuOCEWhzQLC9KG/dr9HxRP1+MofChET+4B7DUKL4QQ1pixKyNR7HjOiGlcQ4q6nADMqzybPQymqmdgM9qt9947MObwv9U4rUwF3k+LgoVLyVGqSfooxjrrs5NmUsO1Ff2XOi1BFxBCKO/avbWVcOZzGg7gPare0e6eGNs3qjfVJhXG92UcnVpVoowJmk9n/GEW4qAR6Fdrmb46QdXC6NnB+9OjplRatFciecT/rKEELemSFV6SJa551sO5nKe3B8qvHzFwZasM7rqLFTOV2hS9qOSBCCTNz8oAzr6LgO+0YNewQXRUsHtNRmgACkdPggvv13iX0Sn1POVQAfXbl9pZbr2zQzGpg/YCvkBfKe/lbVJ5q6mADeVc1kq/EXjzLKCGKXP0sYb/dwWTwLKlSgYt8f/xaAMISIg/87vJ3nwAwTCyCe4oHcF4nqNNubb7bxKLeDES1SQ9PYRD+msJgJ0WYCnfSXbAk1YmGmPIVileFV5DKc=
    POSTGRES_USER: AgBcRFcrl6xG5SzG72vLfiFiiW9TH0upTspLdTcOSH9Cc0OgRe4EBU2tWutf/ypId2WDwI3UHBA7S6Eze8JCZkcf8Xr6Y99paWVCqCCVGFbXnn4G+MGqPkDhEqhU2fqNjaFPv1NK/IjodqN7MuLPWd+7i4HWDMhBCNC/lWbfjYQq5SaDopGco9MVgdU3R6z1l0XgPVAnYMFEC55MorQXWh1+7ho1LMzkLWS9UOZrt1sCJ4e8rpio5yI8mNnXcLDUc965ZOKpkazTvk0FpkhBf8WhnxJ+bpKYCI5/92v+VNaHk3yX/p9SI3HHvpZomzMgmKEXaDDgdB1RFHefjuERWG5fBO5SDKXMuGkK13rNn8hcnMJDBd34KhYgnnV2kDjPh/FQxBKFBLSg70AQQW+nUYJU/AUO9W6/J8QmFK3BcEGmGn6agxPD7X5Gynnz/tRGedFrnZ90VP+O94wjTD7J34M5lzi5c0h7v9KX5xK4BLUDv3BFKoDb+BbnK13zThd6yMYeinp/3nBJ66MZhimqOnWVFv8x89NHa5y19xByzG1TjaUtnzLtoIqDa3WrblwnONBmjnWHS9MGU7B0En43I0Kc4FaQwuRqr0VcZkdEoqpJF2o37j6rFFxLpozGcZxR0GvtyoNafhFj7s/xTS+/M/qhCPXPou0+4iyY/fl/Ydf1NqluAgtzE2XYITQuPqL3UAHkTEbe6cO2
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
