---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgClFW7+Qk3ZJ5HEcMFvvQUgRRldcGUwIRj8R7RdUp+gv6NaMXKUqiY1eCWSjN4/NLcJuSPIFtH4WqgX5+iMVAPqU3fyAK0XsoGEXbDGfk5VL02FNKqkiBIEu6q+gsclBuaOGP2HODb/yBGzyrQ2a2r89rIVTyqdwjGLjsEg0nUX5rLdEsSqVFZA/YxVu5XR8eRvltOl0hLD74/jJB8uc3szc/jtbif4p1WwLdBasRP1Kfd9oIl4wiB84jPkAGfCFJw51flTlZSsfrDc6fXHuWFUqwG2ZdWGkeOgFl3kCS/odzf76NS+IETxNfE3BJcGtKrrUjr6mRF/GVjG3VQNVi+XcjpnWP1V1oCzeX8gvApzD+AT4CTQYR9ila6lc0dml87rtluCObVL6EHTOGABgkHjLRBaa17ruQ5u1/Cpb60YgpL8ZPK2nNbS3PVMrYTd+NRjyqA2zOG3A+tc1CwljTeVN/gB7XtssfE90h454EpzoVxNWkrHw3yzDJTQhGNwIktCsC5tHmQV3DiwEpKkgJvYpx4s8lzv0CkG5CZ22Ql6/TWo3/8QAOgq6Ie+VgRUUFCfTy3rF+26iGAn8PoQensLqkToeuIJqYLPoONupRqS56hiDFooW2W/+hX4kYpGFd62032+/+VOzAgKc1tISy23V4uRkiSlNHTIEXeoLLLiyxyVuxERfu2nUfnCEeKQyK2q3oLzC/hpXqHEGXRl1aY=
    POSTGRES_USER: AgAwPvxZn9wqKwdDnGK56BkkmXNfih1bfi4b2Piuryoli1JP27Z101k4LWMpDn1XbgzUyMtSPe7ueY8ZJK/EhSI2FJTmQQx0zSw2IrHjmi+jnxeH9HTjZTkndj/jTevkqSuF/FK+2zscU5R8UQSR3cXQAmwlSQGsMCcxUbu8vZ8BcjALcKr3keT8TReRBp9PT3v6WP+TXHEn4NK+sW3EDwL+COuZobjQg4V6N1J+vFQzq2kUd79INr14qNRBPx+05juASgaq0lV8HDYxP3zXsf50kDEUYePmUXvqhqkuk6nOs3vwTRUkNTFiqpadAaUkSQmEBZwrS6ORAmAetdBKkeyZMkfgqw5UWv7EJAfSByOBIhG/TpFGTX7+ggnQqPL+l65L8pDfcTTjiEWk9mcAq5np6IZTl81edGSsD8AmjBtQxaMeNGo+TBJlFP4xzV007cE4xml6Q6xnNyRydT6uNgJ7F/0t1jwgHMrQQlyOnootKH6ujLnqJkfzl4plfTa5Ug/PgrwZNB8epQnJCNfbBj56w5JStIWOS+knNKxn8irdaFZIjskg85tLKdM3e6D7Xi3aM/4W4swaDqFNhc0Sd1wQeTGDjUL6O7MWg7C3M4EziKh4xyuuN+m4sBtJ0JzwgD9c9/tZr6MO76ob7O2ZOJKdAK2L+iZxM2RU3gJfzOm5RTj0c1mKo4HAF6IZpQ13K+xxCQXIweOi
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
