---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC7TPf7ARL2qXAGkt2zUIMRvx6OMzmqwvWlq9Q7SXFSnvG0wbv7Tdjroy6ocPLcxt6Jsi0zhFUUdx2tPZvLqu5BPol8J8Et2H2Z0OM33yyAaNdJKXS+xVtTlodUR5N4cZ2fQUZPqMii6qg0us7efaNjoX7XFo+aWnVSuMkfYRGFGRfQdXaYhuzw7EhUoUQ8zrdT4+robieEAy1MvoyFsR0TLRIvyaHArjt+uLKsPKY7/C28tpvVe5lw0V3uv1ljbVLb7pkuOncL6CAn2d0CZDTOUNiNeLrfMaRkLAT07XsT9yARr9Z7ckuA3UR020BYVHo6aGSqEmDMZdBPfjY1toW1pugpR41tXZ/bzcpAlE+h7R3sRVVjqhyRQad138oNXJMdQab6zm97FByi9yQ5zxT3jw56bJ3Jzvl3o8snlGA5c5eRSqsjw7y+L7kQQs63SdyXbuTTwdXvdGADQBtdoI3elhFG5Rp/VjRMt/7LpjaxjzEmrPcUEZoY7PLX2B80Jr6V9OSDxfaOSAfOsIxByzl/IYYcl5X4YC/Bm94Z/48NJ4JCHkaDgmhFRUG1NmiDpRmYEXAQjZ+HsRdKKkG04qF6FTrr6lG4TJnRnO0vkpVuQ13KKDWKRoNFFCcTmNWh8tl9P/feUy44eN4WI/oYXAoYtfq/heiwOtexobvslzbmG5ej2/UASzob+iwVailX3DMYXe/5LGUFrMAb4RNqMbY=
    POSTGRES_USER: AgAhaxD5h7SiA2YnEgtAi3HzOWe+tYvwnucIjC8kBBm3q5Nt1+ocUe0rtg0lwRj+WMzwuZDjVxVe9RoKAkDyAT1RFLWusRv7Mb/HsH0E6s4Yr9lzpGzn8LKKQMjEA6Uz218qGuBQm8NviCxMQ5guV89IEa7ZrsaZ9V0LPbUYI++QJheonUXCg6x0sq8wiz0wGBVQU18enIIH5rLnaNsgn9JQyBbJVUYLECD/ZGnH8cLi1I7v5kKhl7ABHHsGq+inrlWv5vLArwV0bJeB1zXUmV9lgo+wAZuoOylS9DbtQzLO/+8l550ocBlrgzbxQ+m7/hzjoVlnYhrezwVhV47NIeCRsN46J9sDxaXLI2abMfXOSl4TiFDI8X0xv2PbIn+pEfFdQh4FvdmBMa7Y6c5y3ZEHPg/3jqaoCvWDHxRbcWegqQATvuSWXRER1rtzXx32mM9e11u732Vdiv1PcwX0QYupyL6FYhdvTdUENLLF68GbSTuyPBgFw2kfn67sBvqXVjPEUdlYeVy8SmDfFboJ5/mYIFeZq4DkioHq/AuJordq3V/IbEzHoDMF/r16INV1bBX17zKiu+ETr+HCR9+ff9lcwtQicU/OaiZmYiC8gDu8oN4vf9WZNg5ris0yKxuH4qUX3+Z/7FVhhfxWx4lFSp/WvalNXAVIq86jrUfSeG8PV9T32xP4vHX6h+GrMST5T3RZcm1pd4U7
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
