---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCC9mfuzT0ZwaAfborgXPcSC51jBIydWvmZMzwrMVx13PUL/NOhEctQ3lneNr/J/CXQwRuZf3O+f+tnWLFP2PNRUyFgYYFzAjTre2QYdRjWhp44lblnfcG3d7VWHwvzuT4vyvBkcxr7snK5aH0qNYOeB4W34PSWU8DVnqUNXvyaI8NJLRN/NC3dEZzGZtugwgt1xDxDbTXTZ86Q+pPwIkxYHph0+YNQSCdyZ3NIHcJUi+C6LLstvoqVpBaVwaYSGN1rZUCeTYnmMmcUuWgTmgdhMCiNBdYR/cODZn1j5n4mnxKJSbXohQ+ER/56HFH7XbekKZVcYCPdzdLCdbZ81g1iiuxRSzvHSu40MAHrSYbFp1fvZta4q91mGqNCJLfrbLSD03/foI/soIsqeAdxnNi9EpdscvCPqmX1B6byihmWe2SkDMm1uhVvfWM7kcGFo3ssMAtE5sDULIItLERbXFK4I+6kk3ibLnxEVNTdrQY29e5q9fjcu1e0dO5tRIR7FEeDnCDO0VH5FVCw5VOg+TQSVIFqiwokeA5XL+tg5tLGrb5ZgcNB7nNcCQf+6u4nDwT7LxZT8WKPdbCix+LWFGwBmpoB2XWzOuJBsuG00BRLCm0shbpB5NB4ef3ewbh6KfwqLPdWufgiViSPVzPQzgufdf95jiP4DWvjbXehJo2Gi3pKveMh+zrUFSHZ893hxj2Ykju1WsZjC+nkIy2R8Qg=
    POSTGRES_USER: AgBhRwfFn/8frTcOn6J3JvcFatLqENvCOmmzw3XKbOATLqWijXx8FRlGiQyEfteSYa5HyOz2WvmTK+XyqLMrortQiLnzTT06jxss7pXDr92QOa/qrQy85ttkRCoxYLeRHxs47RJQiOU1DUxraTxyFhBelEkBSWnENobyjpVdF5dLCcQedcJSEYi99w4SFKy/883gBjoVXfAQ7iWCa9U3ew48gMwaWULFs6Sqc7rZRRREumtCvSRA3ZASmUx5szxHKA5Cu/V4ZVXnkNWjrlNxG7bcqWwdjBRM/zFKTvR/7YC6aEcN5YSfxWk5uReOPYFI4Buz9/HQaf39tIUUfBXnNbjRdL1DjZne5HoBwz+DV/nQk8jEz9osY/UiBf9tUS232UV/j9p6bvIxBiCnneLaQYO0EYFIvvNyYdafCH/WoAsuofa7CqyQRjcqPVGBQoJ7az9RphTKaX6aXk58efWipBcjR8eEGhnDonfjlc83JuSv+M4BlOM7jXOgdNwDOHltNXsU+mPz8sMcmkzp+Cqw/u0JaAUbhBrswK4HubZefXRA+/qASCXH/xTjTRTY5sqFQUL0kOCWHDpGKRgQOEEl1n3sXRhelLly1lC4ijK4TCzcgh0PVD4+u0NDejHm7kM71LoPRc6W3a7dgKHW6m//P0cOg5ch7tX+c7m3KmDft16mmJH66Gfl5yNrCa7ZVONRdWpfCPHyl5ZD
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
