---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAZor9t+pCdN8NjnCKn7LuJKVRt0o2XXMhgj2BNBOIN+JHga2cTX6x9/Um9aPlU7NBxu/N0WFfjTECml6IwegovhEwE7sMUZEL1A3HVw7Go8fi3spYdOsGK/YfycyEEfY32nWzPKs93uXFEzOXQjV6AoMaWl62NiY9t45SfcA+8LBr+MpY+zfe/EUiyDl6fQKjz9+7NuzWM/4jo9FJtJoYUb/RJEpPNt8r+4uvlMzmodJxBmA8YULMgGmKV2GEwtJdUWD4udcuSsrpR1QkbBHk7TR9rZl8spTIT8C8rYHj5Vhb8HwJ6jIb3GHRxuqR3jL7fJSY0E1jxJFmh867M+GKo2Dy8OZnlhx2zZSRaHSA1VeB9wl+ymcrf4Yk9OMUPE9kYeLFqyQS9kb/dm17KIBRqM7uwHUXqdRp67IIODM82Y/crcGcdNFBROt589Rb5WsvIC6pqsIBpkPpI7C4OhooWgG8YQO3yZ2+NCsAdzXG8nmM9Uxwio7NWtVx7PA26/s6QCp4IWE8JP5GaGoCAyAdm+cPqk5R3Pa1NtwDRMwjWgf1C5zbY2++AGLYS2hQ1faaddCyiJVOAYO/r5rgrfxooVD94H7TXbvEFNFm/pz8ngzNYsSPYnyZ/+ufLfUb220GxkbwFotfiblYK0KYtejkbtlRJUK0qejZsM/kM/Gg81kcFIJ24is7SIoqYVB5xLXiBJGFOuUROcQuou8BuAWQ=
    POSTGRES_USER: AgBKynuNCPJ4Tn5dweNaWx7XvtVybd4bZC5YsFPDWzpnCDZ2IosTLjOCCTcNxcn7YeNoC5vBZ9R8fI5FWqOlPaIFVjusrx0PGPRPZ/xXNky2/n2V7sdEyTzSPK6CBBM1J3KNDHFbwHUWtSn8oh5Wxoy2cNUyLHCRASw3lJvclOhfErI/+C6ZITvcx6Zm7kbGsaisIp+D6a8Q2DNIHkwGZFiZT2LK64eGjnBXomD5PixjozHPbSmNDNtyY02aVcn2yum03k9X+uhadDEOjENqPCSNcSceH8FnlAsHWps9QIubwVeF9/zKbbbZAhew9uNipDS80NNaAR97m8R8SI9vu5EAY7d9sgvvDitkiWROspvZuzyJKFTo2b7thXmRCybpymuU/zwrTTb2fXplUH/mfJ5u7vuUT2XuEAqsYSulgBFzBzLwMkX8EtVParszr2Przf48JoBHFSfaySDhzntn7R7qg2E1RYtFjmFzx/yaIScTM63WzV3E1zTHZt/jY1XKrgdAweiarMHCQThZd8KEd/ine4FicrBpQxJ8mn9V7jUaoL1I/gYoemGaNG4lAD/ZAXSEdfGvbpxhIlCws00pkvTn/fYKVsTbzjbZ/GxLlFRzQLZNqVKgWXzYUOu8UgC/mGAGKPiabpDVdfk/OtsxEN+FLm5dCJDD15LeCTiyFjbXi7lHb1DZqZqxaFX0TzAZwbYfAH62lZOl
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
