---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBZjc9YKS8aVhiSpAVohWD/e1E6z4fAOScw94WPYF5gt0jMNzqKLbZD9ivv9IBJEDHFa4BoJDcze5g/Ij3m4+bxIrXjT5Ccx/vG3S2crihaMC1sbLe7Pslc5NCegBvmKV33wV8PgSY8FGOraj83Rb1XxONYFJ0AN1hcIvnrOncU8Ndgb0cMe6BlvPxkRa8kEWVVsXfezNHGobo/RMatfEtMPTyXax137LHl6nAf/7h8za8RH38/9LDUD89NHmJpFd49Fjnvr7C+M1vQOGbXQii9TJqn1OqDhwTgFYVuee4RaIbzYqIIIlt1/92mhI3hBBnM9AZo1rHZg2CPnA96qYH81Psjwr9OFJlfUOfOritZdlV2SAT86MhbwbHjn06/sVkGf2jlvjRi6Arp0QPVq4Qw+Tp5t8aj+HSv4CT3oaovxLrPIkif6Zjw+PvhC2h+rDJ+wLCB3VTLIm/+vnbEuatlpX1gHJmmey/Vmb92ZgJ4PCPVqihYsO8HhOqjbqTSm2iWwwQ2VpwDhXBQiIVvuxgeo1tFSHzad6b2El9NgjNrRImFu5LecBPuPHLm+ZOPVH+nfwI1f98f87Wh/XQl7K8kKNLcmxE4n5+z21H3VFQFf0zHRXMnFaGcO4W1Z1Zi/bD5EdCKqL19wd+RkxkucXoI0QzHW2ln6/HarnZQkpO7h4G0NkTFBN/d07G/ZUU4u4Rve/AQtddUOuQcQqXNG+M=
    POSTGRES_USER: AgAwu9W+Hrd+8awP4wTukPD4G/3EUpW5/oPqadynQ8Ym1fXLs/5Sxs5PvcJKdc7pNKqMiiuzAS20Oimgc6S3RK4w3rmXr/Pv4zI2GCaG7zP0oIh0ySQA5fGA9EjQv1CYmXj8ZfdIHHuJVU4eJG9ubzbU3PJM7y6sq1gLalm9h2WWr990Ywh3m7JIel6leSIzXhwjT7bUnWOpV4qoxukPk+zLPj2+QiWRSsT9qi99+ecbltsiWqkAW78804O+DmFa/95OJI56wS8gDXnvqMUfmaYYsbw0/l0zOqNxx9Hp4ZtedyXTuVXduRoaq2qV2wR7gNfXWwOxgfRJXDMDaWeMfUCgGx5wC4DBet9IcK6984vR0IWKFSmkaCIicbv+5kvO19p7KGWXHoWXbT1xgSONlHrcslLZ3MWzS767bY6XakRrHFCa39CwSpeDN1iz7jf6KONyTKQxrzAmbZZTL2eCjP37YDc0JMT6d9Vm76GX014yh3tAtVm6xxbuB3vDOsFeG2g02Y2K7pUV5DqhvjZiwIVQmo91OIqacRNQ202PVYekuO5VL2txa5cSvGLAwuW3FuVG4+nkudmOH8S+bqFmF/yihp/Me0inFcpuQ/rjYRzIU1xpJANK54Vl1+3BFVe/COI8nm/1wo6uNibuZ2R11PSUeJ3gbXRHKJU57LrXut34Mzcj5UOTM7vmZC9pZ/RhjBDDQViwUIaQ
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
