---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCX3NuGWXbQpA1/t2QKqEFaxc7Z7HqaTuy1pW95FM/TXaqGbSh3cm+nUfvY8zS95gpOo2slJ0MWJcNayU50exShriG+pkYW/jLcJizKqxUTITNJ3xfPXHq0mwa163jrmLbyP6RrKf0iV+Yk4TU6GRNwYoVKO6dfT9YxaVIL6+JkZgfQ+u0caAVvzk/PgoAQaN1zkZEvKbYwp2pHK+svxhQDeoW+w5HTzKDccFhZfaAnQdM3muFJWLB1jgLGoFrOi5DA6dUi0fXBBpOe3S2pM1egqMBC+WNhqNapGFnFXXh8bbdISuHXZxAx6BvjZajNcDnmgyeSiR2hoFYLNfqLrvS1KoVWyaxJ8hfFAZHEmk5KpT1btfvKD+WWKeALGXt8HVMaNxmwl5qHCPV3EnwQl3uEcZDrixcpq9mxFQflXF2lra5UVxhAmRPvOL550/XmLkIl3COB7fOXMCuxe7s4pcEmpfdKmhzHpWvRgMBe74N0wMAjpM6KxtVHo97fk5qMuOPimXTsUs8Otx9glTDdLJippaE1j5AzQOmIx8nJXH168NZlO5FQb4g6GvvDd0Wq2593PJfgxHO3qhTmIeI7ND441M4BDjbBbHR9Cb4DRWK9/X6cAdU94kbnksDzSTi+EGNhiQTddHaHnUKBZfB9jzpbJElpUvFhbn6m2CvV4jyHb/xht+h1NIxif+0Crc5HzfxV2SPTilbI6FIYN6CIcyI=
    POSTGRES_USER: AgBglQ2O0iXa2zZ18/epYnnaHg35Lsr0bHsFWbyFkr3igVB8jtOp6hrKXRLlUIsW860ZQ8f5NqUqZS2aMGqqTikqBz0GBlgJC3/xPzb/7DS5vIbps01pbgktZ3tTumL5eHljgyrQcEPD17KKjidl4RgsmTMo3s1u9k+QHWkyoGnHWKCC4tWPLWz9qcSEmoPvpe7o2urhdfiEwx1hlQtICI9BlnTsPLaOk7rw1xqCWq576GQ42KEGElTPiEUFc5xT2VXBpA3WyLYgSlLRnyd8Gp14sZmr0/4BIm2fhZ00GqFZOzjW3URB7fPMMRrp+uHKb4ez5F45w1WoDyADhLSsjn0Uaekx3tR8qLlnrseQz8kPDzXrDEpb2lEz+Ju3mdsdWtTUI02yyuKiOaqZBeO6jd88OxJZrWBMmX/qBtcIbQHAE8HwzLFZy+YkXB58O+wwV4XkDlC28DstNd/I+pqIWo0ZgA5nrYoOE0yy72arWl2yXOG/UM+JEcxZcPrYbCZ8sQ89HBcb0U8ycfW/aYmGuHI6slfzRxkHHZPzAdv5FSkcItKybq6ec15b/QJm1W3hrWPBrCFQcL+QbhRzJH0B0LTwnkFkzZjYuf8tcda4Sv2Qp8smG+UCRVeCjhayNAphTa2rI4dWcXIiHp2RK4HEFXgzNcZudNRlw9bRdTVzc36pZbxpaXGrf9HFbwFS9OCnnruqWsQPwinU
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
