---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBe7zApQxUpF6BZVxRqT8Tu/UPwQscSffFWeBIHK/vx5NkseFjxmgQdrY1aaoEoblsqjhc2qZ15znAu5U7o2ir2kNdhXZ0llJCus9PO/Z0BYHXOEJjqCj+8tmBORpIibqm5gZ0q7h/O4agz1nDqB+Qo5kKssnGAvvRL7OB32QdY6c8ZmNTnJmA9/HaXNqAnnCopYVWkYcX50y4qoGBgVUUBuBxdqZk8l/Iwb9zzBLBmbm+QQRrAB6H0WwQLBx3jXnjT+TbpkHYUzar0deg5QmZQJOvb8wYNkTe2zwIIcHTdw3+mA/iiB+xfIMG0RDUPJggQTYf3LIs/W8evRs8YFEseHJNbOnTX7grJzfHMTbIgCQhi43DbyBf86uyl4yiEEA4d6aap/flClN/5oz9jsduul9It+H3s08lhXoAEEWoiBN5DJ93i5Tefdz/dX3Nz4tZFPLy53SPoBdDZi1BUlIiwM6+X6YFLzIRY5wt/kD4eXdDckgEH/rbuCKAsCGvqFlGoVIITiD74nPdzr23+9iDhCwI2CrVgKgvCsu/TvCMMY9gh8KsNgr0UxdaroDGuKB/SZfJTOmCRM9/qFZ6rujBF3ofy1gW8fFdfUroo8dKiFmzoHj+yDaXJEvia0dN031DiQ0+RNJDqQ7nTzNacmR6YtLjKcprci7ej94OsOPMjR7IBqDzNaaIXOJZyRBEVg38OfsTJ0A0zkvCe4RhT/Ec=
    POSTGRES_USER: AgAheelBs1eZAcpYLxI8b2fah0Fp9ebmGjHY4mK0SEFiCfCjx8jsX9n8ZxQMACLy58FWmjuDrydfcjj03Wfk03SMDtNkAw8jCQuQoYgN/gyYwlavsWQhNUM0Glaykyy6DkLX+bTowDAnUqhHwM3bPjlg1qI1yBZJpuzLgQyzqVIhhSm+o/hmaUyzofX8iGagjOraG3BlhHNT9D+lx9lsD38+g1xaX0B8UoWL4fj6H5RvASIocSZJg+YkBABQprqvGEZJLg5uaCXmyeTMtrdYY1gZvxY+xa5ie1UnanTY7lFOnhcNeW6GspPVlEKaNmTC0k1gLzFhs8v4bYalTBUaw8avpx2gS4JisRXvBv96nfg77J+Ed+6wr91mEXprpxbetxHOBDnx4KiAjh6M3vkLXuZ833JOXYhuZppDymDpsqhDl6jTyBIuDOKPqkh7W872U5rTtH2QoImNbSIv/HTG21BHeAg1q2zlYS5G0wRq7deTbZMrcEwGl2GgCY04qW29V47pt9VQfFRuuA4io5nYtHWXVqfhfzrXw+ybaUNNlTpqs4GXBLCgQRQR63w63LpT71nLdu6pxrR+VFxns+9KERfeTh1ge161K27vITQUFQuvM0fe+sh9lZt/NtkdzWwrmLAB7BAkFqV62M87mHwr5rHQnGJxTSGf9NaFhq3dnnUe0P1FRy0ZAkWQXhWw2jntBx+XsUmivxFJ
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
