---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAV5FcGDq3zddcBiynde5zaLFTupWGrtDoQuCjA9LPR2iic4j83o33/I2HlRcPVHy4GnbCk3X2kqjABB7T7IjnYs0vm6jSxeLAmsKQSJADHAPfZyEgTQP/EA2g48BO9d6xlUFfwdVTv+oaMvEGQGPdNHRFgTFcAHxeNwwGb2ER0FvfP2aQEfVWscCQAKUn8IAbrgjo1tJrJVIFIHlHqfLEBTEG0IQbiBqXM+wL2W8HiPP340Q3kVqQrNfx5ip0vlTE09JfDm7+aAmAtKp7QO1W6t6T8qz+GJnc5/uFD73t+d6DUoGPTzxvK5TlGDbQvMcZWypFiyZ0s93zIcishXGSoIvRUZ4/hbrJkqla5mAC+q6uFADE9i8YMPHKnwJ+XVNBKcxqkbP+WIdr5jHyqCPe3PLnPsDYAlVgFMPunAOnWDa4MK638erveafuCowqoSI9Vzq4rs4ZkvoUNciUvuJd2k8esApluAoAax72loJt18KW8iEIoIPC+L8mhzJ6mXRuUeXf/46uzljijzSwr70dRl380VKLNQuIL00hn1ZwLXNxQAIj3f/DXNGSGLpqI5V40finEypZM4BEW/HJchdS9Bw9XwDriAHFUdh3QZtjFrwV/Tb6IEyS/mB50sfN5izKii7fbEUc4tCINNHzy/EuUAAUWmfoluIbUDXruhe/76g/V4kU1XQwQPQ4IOoJNs2/WGARNuX0GWmZ0Zsq7FXw=
    POSTGRES_USER: AgBrRrI55SPStgVRJJGEM0J8hle1qXcWNldSIU8R+1Imn+A+Rf/ekpu7bb5mgFKsns0fIK6gU9J4M8TfSLOB7dPgwkHqKjDbI2n0FmJJXeRGcBE70puroZK/kuZFy2LjXOV+1lLQ9yOcePrWX7oA9m57le1sow5kkBkqm9U1R9CuD2xJF2l+a6gr5Ii6u821VIEUPPRKX+yM5tDldEZngejRKtJFp/Glf74UznTtsBZI0nzvJmwm9q3KAvrBNMwwCRp57kh6RUh02/8D8isxaODuoq6VKcWgayVK3MVMAKnFCrxW27sqEf11ZsgQz8Z4Q+NQiD1Zqfu7QlY0yWoR+b94oVTykgkwUlBZDcHZ2FIBQXRRr7ajT2mSjzauCMwGLL84cnR4l8E2jY9pgErJL8P23ShQ7FGzni2nYRRsm0FarWtm+4hBOvgw4WE8zh56//4EwDmfCjgM9OMPhNQBwA/ktZ6L7TdPXnLqdb96eib5DSxzlBxsnLiW+z2mAujYtHVdLruby5qMyjJdD8BdHYDKUZz4uyimhdw8s06rGvGhLJj8T1ErsyhxrFWPYrGLekXcd0xLE4MMJM6HJL50dFqk68KvN0dVj6hequ9gwDYONqlonxo/BEfyqAdeP2cHtDDv5N3X0fOqYqz7PSDkrJm6TgacyvUBhZcYKJWtJUV4SDAVlZnLaB83p6SXJcxrKmOPswPUECCs
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
