---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBBsurvJr+MylFYIvwi3i7A4lhf6/xkxkzDC3CIrsZ1w4Gz+NSKkdWaKDX5VNVJrkcQB4yAAdOXyF8LrgTjz9SP0VVCx7qFDWAqKZjlKeVxHrtOP4NnaD1JIjqKxMVLpl49cq07lzeCYbzyfJ6ofg7aM1P6DA1BbrnVVTJ6n44JgoY/4FklIt6n7Rv2tABS/vYLOeRYV+qsW/Is68MjHJpgO4ql76O2utv3yiPp4NxTvBZr60NAFNXj+wHm2mYf+q14HUhQ3ZVU+/CRrxeVDxQ1XIzwZtDaz3xvj9UeitbxFb3UpOsm0S5c5FvN9GNUtxemdedj/nDMzGN5uX7zp+MPKFJUWs70eWOdDYky6Z9OuJZWzxKhvpUpHrMFEIo4fssB5UeGHb92Ea9OCD+sWLUOx4XMctry74K0WysYfE65QHr6Khzcad/dJkchKKMQUVVsuL9VSj1SDmOA5bqGyB4UPv8S+dF/mK/et4utilfvv+PfWnCnlkWDJ/ztIE6nC9F/mjCOZKeVvt/CElWAUCM1OqjYZSOi76w5KUc28f8qc3ozubWevOva7FCyfjHcVB8sb/8O/Rsb2L31u40Qq+gbPee+bIFzCUXEKDrexf10wwMedsTJGUQrddWyEwbpVaW5yMKdUnJ0SrrBJ5nDTogPqeX188l8+NncxWUXdmqxok0VirZXiIcojyzdAZED2rxiRQsm7VFrqap9phOQR9o=
    POSTGRES_USER: AgB6eSd9VWY7Yr3f38U5FMO3d9VtdxZnlxVTTK9xWuTxJ1QM/F3LrWCippYHle25JpKwXE0ghfbHFnCf+4KMAlGV9ti88g42agcWGp4P84NNr+Zj2LPaSTO0Y2Dv8+AhHnWMJbPKW0JRp1yTCZWv7WCr2pcvMbBQUR6T9Fh4JjFox+UzjsIZkXHHH+1AdE2ZVmeDKXXHb9uqQc/5OzLcpoMs3RrEqWGZ8ZxCr9mJQts/DPMlIQF7P1YVqoKMo39QWDXR3V71hwzJYYofLgUxuPnlRLUwpduvqfsLVRfGa/h6xcQ73tUIL6Xk19RUZXgrVby2XxNH/fPMsR49BfdeWQ6oiMr2PppgDbp8jPRT5xuzL4v2cZ3SV6k/OUDWJZ2GodqLJafAXG4dhyl8nCtbwbHBnHBJqUimceEM821OTOIpQ+V8IZsg8ODzmXpFsCAeq6JN6GYM9bR4yxILYpbzeJtCpbZp1JEz1OoCQXzqVg/hrSLpezdzjo9033GRmDhOHjw7/1xeIj1GIjcv80Eaokt6NihmK/4yK3Rg67sFNnHZjjroyXtB0/pDcc+6DORdbFvui1xSxke8xF/ppCiVB09euEV8Om5nT4p41Q7vFIxtg1UiEDVm8gY2yOkGbHL7tHyN4OdvB9pDF4PNtCQzuBfNYLoe6Nk/W2XxOgwFCgjOclE0VE3sDgJVjoxaH92UbC0quFdpXNum
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
