---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCGha5HVNS6PAyOF6i2JlCxyuO7ZgefT3SwsD+UfcMgvyT4M76C7KI9mYRrs6bjVXjDaSJt6n+yqmOn7SqI0h8wD0owwFmXnXIeFF2McIIzWATer7KlC0NdXLa/CLYKJ5x07HvjT189janUc4HPaIAu3iazKybI/DEJNVSDSj9ByvhyPuMXTNDscSMMdF4QXp7wC2C+r4MRlnRLAPSyn0+Yvv1QQzQBpdtQ/7lJVXQJPkNXsn2yXoNcCYq0P6kYJvd0XOBMtjXnYMPQpsrF7ymZ6sNSfug0e9nt9qZ98kAHoJsakm+gm4RdYp0SGW8/5Z0e4pC/Ch78ob3GAYUyrfuihERe6F5pyIOZSTbXdvLsu7kSANG3cCI9TDhN2ru6V/+IJh8HNHenBXk7wzjlZ60ywDpzB3I70DR5cxfnM3+BBpsa6rGs98o2ly0Kf+dpNn9s5+jggwi8+gSHTUq6mtAXQ0FTQd8NrLoDNNwmZAbELIh0AIsZbwa+Vd5upTi4y1JUYtaGT7Q9jbRShZTlwDGzYPqhyqtjGjAOifEzGvgkAplA9AucsZnlIxubeYTDf53B58IdnpAfrWM+m53eI66vV8/S+7hQyOAg6lnm0i5b01kRdzTLVcMfykVnpsd/lKmTe7RkYQuPoXFY3/dJKqe2TMkLvfj0UwpLY4Tj4WnXGM5WGYjCgSUjrRJUgZ8Cq3kFHdO2nBrxJP8JiOm7Tgw=
    POSTGRES_USER: AgBPVgW0zYVCnv0Fhmlu2gCzUV/nQVBP8wn9SKN7Md9+8E1JbK9YH3wQdWaxUYWUmgK0An9Ix/kIn0jstqJwivtBxLu3+NhKkzO9YFXKNZG7i0c1Xg6A9DcrgH6mEp514xrGPbOmah+0fDks09RAx3UZQ7KGysSfYGGBIDw3QuZ5y+O6fKbwYrueTnuBS+rWtu9XRvgrMauSRqJg4qhQ+57u8dLJSr786LxjKbM8jlA4cFWJVUqtp5Ra3RJCHjRf8XzdI4uVOTvuV63rASNh1lhYBb7m25bL/h2OV6siGXAyoemRIEZ5P/nLPdMlbKBybJRqj0RHdIvFCE8Erz00z4THl2GmLzjficiNAAgUq2GdqWj8ithPcrY0WYSutMuNHs3H05X+N9EmhYc2RVOjpgqiKnVqn8AX/YMpww0EcDOTczP4rvupzKCFq5cDcFGRq0+fHGv0ULdRBc3OiWba5yFW4ezcZ8XSfksKVN1NvA2jUFupRKONiZYQCEBa4mW7hTWhjqXmqG1M8BjFFv7exzQSRCpjriNTmxAS4bD92a1r1Et9/FER/wlLYrkW9qckAl9ykjpw1ne46a7tUyL5A3BKPtPtJ7uSOgindWcixxikV955m3vyBSEdbjjfq9nzLxX6GUB9uis35KyiiEEeoU3vZIYtSgQqoFY/Qyf7r2fKilz8erslSdDEQJ0FJofIz25Mw60oCuo7
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
