---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCWJz65v9egDV2F2xRZZH4UDEMQXIu0FLXHoVB19Hd9y68cZJ9/F4CCpVr9kyphV6i8S5F464eM1bkY1clPhzizzVtn3Q1O0w+FhurZY1cCu+pgU8GmdzW9qVVX+kfB+HdZCLoRGG+Hsph86BCelOzVe0qUAIhsTuW/o5HZzkN9n5G3PMn0lBTtwJJt3rUXgEwMJ8hkXoJZcmSipJyMEGW2zaihBJGZjx+9dzwuffUvNZVFJ8pBmD8YvSPB48EZrbE2Wvt+2ePtMj8UTXZ77ntLmA/ZYKkC+r4UCLBhp73M9ujpHiCgip+8W6NY12VNweiQ4teqoZQbDz4Zx/SrZDrsxg8DxdFiGGXs0+IW0h/FKgrYZtBYVZDuXJfMJMQMAQeVJIXr/389M8rZ4hEb00szKjSKhqJqw/BC2Te1B4l56HHtK9fowVzTW6n7p+DCEvDn7LNLtPt0B10oTMiHCbsQpvEppWBNvQjU88x/K/P28IiJw0bnAfsV0nFvoZcAuGfzYHDKLMAiUxWcOxWyanzfMOSYIsXbKpkOcmgSTpCTJnQnoyJQdfFIv+S8w+pwumfbXfi5hy8qIyNVqtyo9719irfGllHE6YSjqUh4vKgyIuJTbEMzG3salEkOsHaipqwIgNy7jEZLyWZaMxIMvnStqVo60EI8KElM/VPOcc3rz+T+IwQxyOBUw2WTJU8i+IcmFDwcbQC/7lKaoKIKsvI=
    POSTGRES_USER: AgBX21rdF3A8ItdnWBSPfX4RJJHhh4/U3A6trbnp3nDbXmz1KQdPjDfRpTpTzT7hHzJof4YxHg0OK/IC/7d1g2kQvwZR5x0RRaglZCwQ7Z9Tl8rHD2/rZxw8lisUqhWyJRbRv+CS7Y+a7k/q/ResqAyvSWEYre9NEmo0K1z1Uo4lZed3hM2SJagUSnKOhFXVsR1MkkYNNce39Knvec7tML6aVtIT2El//XJhH71NCg24qzS2UJNLZAZ0eDEyimykhCtOMcQdeEjjdYMarcB5ZNRwm+JHC9BoMc8ETaPCbqGLAU4GRLJ47zQWnyOkjiQjE5FV+yvkLGLAEE45QApQzDha/UNA911h9fnhcTy3jt60JmdY3BZnH3gYb5r7pytE9cngfKmH17vjN1mwgufcJsZGOM97TvD3B9lEJNZgp0CgBKDkO3+ITHKirMSEAK2xPObnc08wgYDBpd63BalZQs+NAavr9rzfsnkQCAP5OLdAXqeFLma9arDMXxWkUb3aGngPXDMWYqdfmfwjPTvReOHDVLvE6b5OGQdGDngbuTp+Gf6lWMlVLtDGw3FxuxZ2jPwvy5xAc9Bn0VGtLJpCP/zYLBH1mVUa4mKEztsa/Vx8hvztHfK1F5NI8Q4h74IcuArTDZEjm40zvgptIIOWwMYQJ4ToYJM0Pa3OSiWYU5jVJCWRytf96JQCIcPOdN6Z+zeYAvt0hO0q
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
