---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAZNy7yVUHnAExA7ZTupPHAo/W1m+3kKsd+TNeO5trD0c6vGvQAElqlK77tiDFxThHJWQDRGnVKYIj+W64l8sYSSyL3HVy2l6dGBju0j1AfyAXpWC25idGvvqPGIRkRC4kdzPCGfQ9x2t3U5wDwS/SzB/zYZzf5nIeUPtV6pBNrEc4aUYoXztkLhqiD4tnbtkNy47N4EHjU4PUSQUcaLbAa6TvrsnfP+IJKa1Q7sjyADq10v5aD5WDC2ZLHoInEYiA1l3O9NzRsI3N8bZeounoGIAfWV0lp31KxOOHZDWUjVFwAZmw2D5PziHKOlPrr27AC0wtI9NGaTdrz2IfeNjwrVUopJ7n7225pi15rbOnifi/LcAP9zBccZOhG2n37QoABMgEXu26LjqwbLB4xSyEmgi9Qt692RXfHw+BPLxPN4wRv9JU5YYwpdzn8AwAJbRFlU1if2n4Aw0J2kmqmnYWpDXCJqlQeQTYh8eLGg8GScz7zYZ2EKaov3f2KG5Uh1zBZnWRWWiFGQxN9MfnWUXnsvE5HykQyNO6TM2q9UvwxKsoUtkU/eeRHBKD9wCTgg3lRnk5Dgv+uZhQFPd0hwRkyv/z5x2QzyeVLfHWt96poQwWCWaao5Ol5XYclG3iYc+3te8JH3aaDTNXhi1sHKZBA8YZHrf2MzheTKDKw+8PffBEzylpcEsTeB/DIV6oeL7EhWjOYyCLxdO9mahKHrmg=
    POSTGRES_USER: AgBb0MM+fAIQ4cn+DxOz1WIwAhTTAM5oPF00Z48X6UAOIJuFVdrijQPQ4Ah3D/OSQ3UJAi+u3z1NCXiSIF5UHvQHhllhgPQjVJ3/eg1DJi0RaFxB0xl4c9IpKdqFm7/kgGWS0ghl/T+wH/GZVpJwv96C3AgNx24s64B6U8LgcGmvkYYNnrhNCUMpQSsRE8Wdn7U4x5UXUM/x9CiBsSkWKLs45OxDAORe0R0r/GkfKjVKN+WiS5dMrc9/I1YqL4qLdAgu6pL5TSbNvkVLEPxjlhaYmlCd9dVhw0Bychz5DVS7jb5eWJU7docai+ipbQcp/sNUInWx8hOrhcd0S37G0NFiZg36YwfJTx+OErFXV7LT8QPUW4n2pJ3sHTfrAvKGMBQQ9Z78K0l8fVITQpqiEkBSFlcmqtKkupMLBlE4sZ6neJvoILpjt5sJNBU4hx9dznzXaJvn+FO20J2R/oJmFYL9jG+c2woxR54PeVu2+/en05DA4ieCTzA7oMjLSmGlguCH92YSAB7qBrxXu960drSS1EOftgRvHybAc4862e2Z9O2vtOxrHusWDbAf8OhxvbXtMGGFOKHtSL3c9o6hAei5lbUv2WILLNo1Zbf/kRoAQ3Hj+xgSp5jlHfhEat1an3wTH0k9jxBTcs8KNVjvsgR0xQP+4C5cGPC1K4Hk7qObzpJnaxgPXq+slHqRfUORZ3sC+5scvQUn
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
