---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA3Pw4TrnmR7uL146UWjwcyGKz6Sqd1OvQbt+XwR0BD//6PxIzv6NQwMzY4I3/m1oHXZyxOtZ3FIZ/2dhPRnWxJh94H+UofsQWAKpsbZR4a5ciFS0e1rle4qKAHZ0pINsEgn5NoO95G7Dqq5PbXs52HVdzdMrIhNUElGF1PuaDm5Y8p/gXgW38oD4A4eJ6sUp29y9zEVARIbgU/WCiEGM+uKucJU4jWNovndR8/nVTINZZGoz0HmYk2asPK5JpmmcspSI1E564/r1bX3HVCvKboOGR7ZsSVP7Niqq7lfjvKPuGGh0lmTiSWAEfBOTlNMpMbY/Ktz+Co1g+rWmx/ZS0GtxshGpbRIkFqpoLnsHSa6UqCK/ZHArFZlErPLauw8X1IlQpsWfW8QpiNJslvKfd6uO85++R22yFMn1OcAxZwvY/ZcXIF7tNjaeJ9z9QS5IlSv+ZPDJhgZqNzaWiHTIa4ULD0M8ufx2ahwPV5ZNa77zKo6iKJrPox8asyfMa3B0muBSWM+70nfmCxIVgjBRmgoeisive/eDYVgJjzf9CRrgWlfeng/5Wy2huUwO+N2GV9bxj60CxCWGX7aezajkyb0eSsETZPHDJXDQRJogcT/ssKSHKpM9NO/VmFcgkjB7I/o4cR6Mvy9z2MXtuy3Alv0Ijrp1SLa15fn/13IGfB+1uAPJGfqRpckvRKKThHAN9ADS+3W1Uq7gAZc9+b9ok=
    POSTGRES_USER: AgDA27gToJi7YMQ3dTcQEbciPSMW05vIZaPaoq0dxFvd82cJcwSPZolKum2tQHzppGRbc16UbMiTlkb+IhVkbHQgUDrZ31IVjQnKSnzlkKm91CcBp1fUlQNiDzLFx1jOwfxF1VsSdf+iz90/0VD9UjFgN10OW0DmnCIAI1ePw37V7gysJunGXIk52HxloDoy05l5A0XPFroGeWP+Y+O8YvVNvavttC8X7f09c3iipBpbP21hubITpW2as/i17dE1T2MJKz0jCegQqWGn0aCtpSXjaBw8ah+x/Lm5bQunzIJo1pZBnbWfANZNuJ/9rHMBxSBWv/wWED+moaD6D/0ylUMEnu5FWG/oaXLzKAQuDd3DwOMuPRwODIp1wLnu9jDVtkzPgY4OUakQfmXnNilTL6Goxbcbox7t8J+neZe7SP/A/am68jScuH5icxZ8fWptjiKlO/p+/UFGd8g6g5q24IO+OHGRHon7leJxKbuzIfhjoDM/gO3C5D5ut8rhempe8c0MRWKWTo0t4FuMVaGxXaAQlGALpkNdh+wq9rHItxT4Yy4XRP5UettaoBX8NSuTXD5wnOhjuu4OPnzw6El9PUpAfTlOAkoXEhtA4v+beIlqzg5mDoAG7UsAYwc+QdCubFFft48DPC77AiQa4jZFwdNTGB/texzTw047RtvJCuN7fBzeDVlAjt+MCccSINnXfEHHUh8Vkl+9
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
