---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: messageboard-dev
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBdDRF6uve4hFW+UUgEkiedxGKjRznLj+7h7LWsjsdc5Jg77v+COFFLG3VxaoH1RCFF5CWmL3VAaV93Zd6gSS5EXNGmQ+Gw4e4SJXdL8BAw82OHcyqdxegNqswwq9Q8w/v9vkFu4f9HlIYGjg3QjPFesPFkNDQ919VArMpdo+//TAjV2W+7E541idb19rcrb0uexRwJFxXpyU5LedgFgLnciIcpgZKRaKNO2FnnDV3FkWhw7CQQhRSU2tAXK0cO/BkwS6HzcyqjHF+vnxJy0+Gu+JZfx74Aw7Pew/E1fSeWiTirfECmEWoEyoGtogA3phqdxc2MjQM3EhbJGUng+SaxsI8lBYChaeVtZUhGxL02q10ILfC+edfSp4zJlVL27irRlDoxmGryCDMrn1ftQnSiaCZ/emW0TlZyCu/z4fsG0oStFWtfDT6tEFPK6z1M/8pxMaqXGIoC4/cXS+UHSOQbLoj1KBr6DWtUEWrZkHuti13g5knDfFCBNsBicS+LpiXNDSUJ/mAoFyQ77XpW/oQtfCYC2sHCKTCh0gUfX9cK8g3H2EJV6VhH5IsV52JE7oFiIrpZVXj2yB3yWmfQr53QZhs3uyzXSUmuletXTNWtEn15wbes/lWSqzkgz7tC6pyVEWVqo1f16x3cPEek85Ne1NgWa98jsCQSfAxJ7tlNDJX7kcV+iPGXHrpb2acinWy5zrr8VwoUWyCRCt0a9js=
    POSTGRES_USER: AgA21goac3Epy6X+/565GHRXZa7TrwGCXNB0nr/D3CJNcQ2yMJ7BKm/nO/JrMmg5PnHH6Z1bJxj3DAPr0dI8hQT8U2Kk3VZnEx7WDI869Wz+zG2fQ51Nc1CQrEWsofTsOjmt3z/lxATQIl/k9JjHsp7zEbdh8u7BUeT3s9PMaxq1KPOSFdpVj4qmKGq4Kgb/K7ALrgcrZTfF1UohTSMkdVy1IzK0iaiX7K2ORvg92pQ6QnYPkaMTfjfsmFJaQwPZoHchkMwjJXnk/k2Kaz5xWwUFjgPxL5n2AX9AlpvxgGUWbOPWqAdUWJG0oWIFatCVgLvj2ehfMpjIh0F4MPKB4mLd+3250U4Fv+Rwjgv+dNV3ZHo8wXJdPaV0lOzgmBY7ners8NZWVzuuJZzw2PetLXSigx0xDXWbuimduD9sBqVEYyD3Zj/Wh2VzaxjPJml77OSiVC9xAB7kBipMSTInRJM/6ijT+f0dJAFQsaPb8gBwNp0X9NGH0ljGfhZ/j1zdOd8r16SXWJwHFT6lCxWuRLpU/HJUULCI/ocF1ITgERQjMkcCkTedOue1oeAvxLVfMi8ytq+UnThBHDkGlbo9e3TaHh2WVSVwd2bsKU9nBmWWgtxZmANVUNpvLjjSkyl/Jt9ejuqyZZyeEkNT90ij2x0zCyl4gn2RpxZFmRn5oyPz+/kgU8FTHJTWyNgVxTJae1urM/GoLXf2
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: messageboard-dev
    type: Opaque
